### ISSUE TITLE
People picker not rendering in correct context

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1023]
**Describe the bug**
After excluding an editor and then returning to add another suggested editor, the People Picker adds the new editor to the list of exclusions rather than suggestions.

**Steps To Reproduce**

1. Go to https://staging--xpub.elifesciences.org
2. Begin a new submission
3. Navigate to the editors step
4. Select 2 suggested Senior editors
5. Select 1 excluded Senior editor
6. Attempt to choose a third suggested Senior editor
7. Observe that People Picker opens with exclusions

**Expected behavior**
People Picker should open with suggestions

**Screenshots**

<img width="987" alt="screen shot 2018-11-13 at 08 29 53" src="https://user-images.githubusercontent.com/17023702/48400634-d302a080-e71e-11e8-9335-0181e2718e41.png">

<img width="924" alt="screen shot 2018-11-13 at 08 31 33" src="https://user-images.githubusercontent.com/17023702/48400644-d8f88180-e71e-11e8-9465-18773310c101.png">

<img width="899" alt="screen shot 2018-11-13 at 08 32 43" src="https://user-images.githubusercontent.com/17023702/48400655-e01f8f80-e71e-11e8-9eee-76c4c15260e4.png">

**Device, Operating System and Browser**

Macbook Pro, High Sierra, Firefox

**Comment by jsms90** [comment]
Ah! This is the console error that @diversemix mentioned in this PR: https://github.com/elifesciences/elife-xpub/pull/1119#pullrequestreview-178747339:
![image](https://user-images.githubusercontent.com/15656538/49171537-a82b6580-f336-11e8-8642-626769575408.png)

I'm almost 100% sure that the issue is going to be that these modals aren't being passed a different `name` prop for each of the 4 different places they're being used within EditorsPage
