### ISSUE TITLE
Menu component label is not clickable

### ISSUE THREAD

**Issue by giorgiosironi** [elifesciences/elife-xpub#1041]
**Describe the bug**

The label produced by the `Menu` component doesn't nest a corresponding form element, nor it has a `for` attribute to reference it. Hence when you click on it nothing happens, this hampers accessibility (I think) but also usage in automated testing.

Related to https://github.com/elifesciences/elife-xpub/issues/326

This is a Pubsweet component but no idea where to fix it in [its source](https://gitlab.coko.foundation/pubsweet/pubsweet/blob/master/packages/ui/src/molecules/Menu.js).

**Steps To Reproduce**

1. Create a submission
2. Go to the 2rd page, `Submission`
3. Click on the `Article type` label

**Expected behavior**

Focus should go the corresponding `listbox`. This happens for other components on the same page like `SubjectAreaDropdown`. Would lead to tests (in this repository and in `elife-spectrum` for `end2end`) not using [selectors that will break](https://github.com/elifesciences/elife-xpub/blob/develop/test/pageObjects/submission.js#L9) as soon as the position of the element is changed or other ones are added/removed from the page.

**Screenshots**

![3237fbff-5727-4029-8c7f-08c3f65d29de](https://user-images.githubusercontent.com/160299/48495658-683d8c00-e828-11e8-8217-807473f57863.png)

**Comment by jsms90** [comment]
Yeah unfortunately this whole Menu is inaccessible in multiple different ways. For example, try opening the dropdown and selecting an item via the keyboard. So it has been acknowledged that this component should be replaced entirely e.g. to use react-select (as we are for the Subject Area Dropdown just below) rather than pubsweet's `Menu`.

But this problem is sitting underneath the addressing known accessibility issues is on our roadmap under 'Later' i.e. to be done after first release.

**Comment by giorgiosironi** [comment]
Good for me to close as `wontfix` waiting for the replacement. Will mark the CSS selectors as "unstable".
