### ISSUE TITLE
Investigate: Can't scroll editors lists using smartphone

### ISSUE THREAD

**Issue by weimunchan** [elifesciences/elife-xpub#1048]
**Describe the bug**
...
When the editor selection pages are viewed in my smartphone, I can't scroll through the list of editors. Also, when I flip the orientation to landscape, in the editor selection screen I cannot see a the list of the Editors to select, I can only see a search bar and add button.

Scrolling down the editor selection doesn’t appear to work in either landscape or portrait orientations.

**Steps To Reproduce**

**Expected behavior**
...I'd expect to be able to scroll further down to select the editors and in portrait mode see that the page is scrollable to reveal a list of editors.

**Screenshots**
![screenshot_20181115-153021](https://user-images.githubusercontent.com/44775077/48565285-1a8c5680-e8f0-11e8-8011-653bd89ffc87.jpg)
![screenshot_20181115-152922](https://user-images.githubusercontent.com/44775077/48565286-1b24ed00-e8f0-11e8-919a-d472ac42fcec.jpg)

**Device, Operating System and Browser**
OnePlus6T, Android Pie 9.0, Chrome

**Comment by diversemix** [comment]
I would recommend we split this into an "Investigate" task first - just to see and make a judgement on the work involved.

**Comment by hem-brahmbhatt** [comment]
This can be reproduced on desktop using Chrome.

1. Open developer tools
2. Cmd-Shift-M
3. Select Pixel 2
3. Go to the people picker, or refresh the page if you're already there
4. Your mouse acts as a touch device. Try to drag the page to scroll, and it should fail.
5. Close the people picker, and drag the page to scroll. It should scroll properly.

**Comment by diversemix** [comment]
Any update on how you are getting on with this?

**Comment by hem-brahmbhatt** [comment]
Found the issue: https://github.com/elifesciences/elife-xpub/blob/develop/app/components/ui/molecules/ModalOverlay.js#L60

**Comment by hem-brahmbhatt** [comment]
The people picker acts as a modal overlaying the editors page. Because of this, we have to disable scrolling on the editors page so the modal can overlay the entire screen, without it having to be the height of the page.

We're using the [react-scrolllock](https://github.com/jossmac/react-scrolllock) library to achieve this. The library also disables touch scrolling globally.

The fix would be to set the [`touchScrollTarget` prop](https://github.com/jossmac/react-scrolllock#props) to allow touch scrolling within the modal. There's a few outstanding issues which may make this more difficult:
- https://github.com/jossmac/react-scrolllock/issues/33
- https://github.com/jossmac/react-scrolllock/issues/34

**Comment by hem-brahmbhatt** [comment]
Fix will be implemented as part of #1052
