### ISSUE TITLE
Spike: Investigate moving xpub-elife from gitlab to github

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#112]
Primarily this is going to be estimating the work to:
- move the deployment. 
- deploy branches to different instances
- anything else

**Comment by g-sam** [comment]
There is a relatively simple way of moving to GitHub without rewriting our CI. GitLab.com (but not Coko's self-deployed Community Edition) grants the ability to use its CI for open source projects on GitHub. This works by mirroring the GitHub repository into GitLab and adding some web hooks to update the status of branches on GitHub when CI jobs complete on GitLab.

Setting this up *should* be fairly painless. The main complication will be to ensure that we have a runner configured as expected: we will probably have to set up our own runner in the cluster since GitLab’s shared runners are not configurable.

As far as I can see it will still be necessary to navigate to the GitLab repo to see the list of deployments, however, I think that's a minor inconvenience compared to the boon of having our issues and MRs in the same place.

I estimate about 1-2 days work. Shall I get cracking now?

**Comment by diversemix** [comment]
I'd say so ... @hdrury1 ?
