### ISSUE TITLE
Wrap people picker keyword objects onto a different line when exceeding max width

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#1129]
**Describe the bug**

People "keyword objects" currently wrap onto a 2nd or 3rd line of text if there is not enough room for all added people

**Steps To Reproduce**

Go to people picker and add multiple people with long names.

**Expected behavior**

"Keywords" should wrap around onto a 2nd (or more) line of objects, not a 2nd line of text within each object

**Screenshots**

Current:

![image](https://user-images.githubusercontent.com/41907215/49169008-b9717380-f330-11e8-95cf-eceed3704807.png)

Intended:

![image](https://user-images.githubusercontent.com/41907215/49169038-d443e800-f330-11e8-885f-384500a33fb7.png)

On mobile:

![image](https://user-images.githubusercontent.com/41907215/49169139-0ead8500-f331-11e8-909f-218d1f486efb.png)

**Comment by jsms90** [comment]
Just to clarify, in case this causes any confusion, the names for components in Invision don't always match up with what we've called them in the actual codebase.

The component that renders these blue tags is called `SelectedItem` in the codebase:
![image](https://user-images.githubusercontent.com/15656538/49170523-3eaa5780-f334-11e8-9d1e-a23401d066bb.png)

and `Keywords` in invision:
![image](https://user-images.githubusercontent.com/15656538/49170668-947eff80-f334-11e8-9c27-b602e0ee3192.png)


Just in case anyone was confused, because we actually call something else "keywords" in the codebase (the 3rd line of text in the PersonPod - i.e. focuses + expertises)
