### ISSUE TITLE
Technical Requirement for eJP / Joel

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#133]
Produce a document that contains the technical requirements to extend MECA for xpub. ( Action from meeting on 2018-05-15)

**Comment by diversemix** [comment]
This is currently on hold until after the call we are going to have with Joel on Monday 21st May 
@hdrury1 @melissaharrison

**Comment by hdrury1** [comment]
Following call with Joel, James to collate technical requirements. We will ask for Joel's recommendation as to how eJP can accommodate us, and at what cost, before drawing up a final SoW.

**Comment by JGilbert-eLife** [comment]
I have collated a list of the information we currently collect for Initial submission cross-referenced with what we are going to collect with xPub. This should form the basis of the technical requirements for transferring articles initially submitted through xPub to eJP to begin the full submission process. Unfortunately, I don't think I can share this initial document publicly since it heavily references eJP's proprietary data structure . . . Given this, I'm not sure what the most helpful next step would be.

We can certainly draw up a list of information we will need to send eJP and suggest some means for doing so (e.g. article XML, MECA manifest etc), but I feel that we should provide the database-specific information as well (e.g. which fields in the database this information will end up in).

Any suggestions @hdrury1 @diversemix  on how best to handle this? What parts of these requirements would we need to share with the whole xPub team?

**Comment by hdrury1** [comment]
I think our only option at the point is to draw up an initial document for Joel indicating what we need and request his input on how best to implement the transfer. I can't see eJP agreeing to us sharing the data structure-specific references with the YLD team so the final approach is going to have to be decided internally... unless there is any way of censoring the information (which I'm guessing would render it useless).

**Comment by hdrury1** [comment]
@JGilbert-eLife Would redacting this information result in a meaningful document? If not I don't think it's worth the time.

**Comment by hdrury1** [comment]
Sent to eJP and awaiting response.
