### ISSUE TITLE
Write an ADR on how we will structure the code

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#140]
At the moment we have `db-helpers` which has functions that manipulate the `Manuscript` object as well `server/submission` component which also describes an empty one. This needs to be encapsulated into one place, I suggest we start using an ORM.

**Comment by diversemix** [comment]
I suggest we introduce a server-side Data Access Layer (DAL) - in order to de-couple the UI from the method of accessing data. This would also serve to help the LotusX project to expose the underlying data in a uniform way across xPub and Libero.

**Comment by g-sam** [comment]
My initial thinking was not to use an ORM but to implement a data access layer using SQL directly, or possibly something like Knex.js.

Why?

* Simplicity
* ORMs are leaky and often custom SQL is necessary anyway
* It would still be necessary to implement a custom DAL on top of an ORM
* In my experience Node devs just don't like ORMs. 

Feel free to shoot those down 🚶 .

**Comment by diversemix** [comment]
:thinking: ... Morning Sam ... I think we both will agree this is important - let's see if we can have a time to discuss this when you are up. I'm all for making things simple though but at the same time like encapsulate / single area of responsibility for server-side components. This may precipitate a good overall architectural discussion.

**Comment by diversemix** [comment]
Sam - do you want to generate an ADR for this, I'm happy if it were to either (1) Contain multiple options or (2) if you are clear about what you'd like the suggestion you recommend.

**Comment by tamlyn** [comment]
My experience of ORMs goes mostly as follows:
- you have to write your queries in the proprietary DSL but that's OK because there's lots of documentation explaining how to do the things that you already know how to do in SQL
- inevitably some queries are not possible in the DSL but that's OK because you can also run raw SQL queries through the ORM
- when running raw SQL queries the 'mapper' part of the ORM is no longer automatic but that's OK because there's an API to let you specify the mapping yourself
- lazily loading associated entities is too slow but that's OK because you can specify up front which related objects should be fetched from the database
- when dealing with large amounts of data all the instantiated classes take up too much memory and kill performance but it's OK because you can specify that you want data-only objects (without methods)

Once you've worked around all the problems introduced by the ORM, you find you're no longer using any of its features. I should specify that this experience is mostly from the world of PHP. Perhaps things are better in Node-land.

What I would like is a database access layer like this:
- each entity (user, manuscript, file, etc) has a manager which defines the basic operations that can be done to it: 
  - `manuscriptManager.insert({stage: 'INITIAL', coverLetter: ...})` 
  - `manuscriptManager.findOne('123-abc-456')`
  - `manuscriptManager.findByUserAndStage(user, 'INITIAL')`
  - `manuscriptManager.update({id: '123-abc-456', stage: 'SUBMITTED', ...})`
- These managers are just node modules, not classes.
- All direct database access is confined to these managers.
- All data is represented by plain objects (not instances of a class). This allows data to be treated the same on both back end and front end (where data access functionality is limited).

However PubSweet is currently home growing a different solution. Its functionality is similar to what I describe above but with more classes and objects and active record. I don't feel that active record brings much to the party in this case but I'm also not sure whether my ideal solution is sufficiently different to justify breaking away.

I'm still quite unclear how either of these can be made to work sanely with entities that have been defined and extended by multiple components. In the back of my mind I keep coming back the idea of making GraphQL the interface between multiple components. I know we discussed this when Jure came over and discounted it but I can't remember why. If only someone had written an ADR about it...

**Comment by diversemix** [comment]
I've been mulling this over more at the weekend, having generally reviewed the code and thinking about Tuesday's meeting. 

It would be good to put some ideas on the table - @tamlyn my experience is with Django which (whilst not ideal) does offer a neat solution to an ORM while still allowing you to extend it. Django does have database managers too, but this is at the higher level of db management - you can probably get a good idea from here: https://docs.djangoproject.com/en/2.0/topics/db/managers/

I also like the way PubSweet is using a similar base class "Model" for doing the ORM, we could use that - it seems to make sense.

**Comment by diversemix** [comment]
Summary of Meeting (yesterday)

We considered the following options:

- Waterline - ORM
- Knex - query builder
- sequelize - ORM
- pubsweet - Its another self made ORM but has validations that we don't want
- bookshelf - ORM
- massive.js

The conclusion was that we would refactor the code (see below) and create our own DAL for now. Maybe pulling in a query builder (like knex) as/when necessary. However, at the moment we are still just serializing json in a single table so we will stick with crafting our own data access functions.

```
server/
├── dal
│   ├── manuscript
│   │   ├── db.js
│   │   └── index.js
│   └── manuscriptPerson
│   │   ├── db.js
│   │   └── index.js
├── graphql-schema
└── resolvers

``` ... @tamlyn @g-sam ... are we happy I write this into an ADR?

**Comment by hdrury1** [comment]
@diversemix Yep, ADR please!

**Comment by diversemix** [comment]
Ok, we (myself @g-sam and @tamlyn ) have spent this morning discussing what we will do, why and how it will work. This is going to get written up into an ADR now.
