### ISSUE TITLE
Tests on develop branch to fail if coverage decreases

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1462]
We are going to go through a stage of re-factoring and we should at no time decrease the code coverage. Make sure we cannot commit code that reduces coverage.

- In order to achieve this we will store the overall test coverage in a file within the repo.
- This will get updated when tests are run on the develop branch if the coverage increases (or the same)
- If the coverage decreases this should result in the tests failing

**Comment by diversemix** [comment]
On second thoughts this should be perhaps done on merging to develop

**Comment by Cooryd** [comment]
Agreed, per commit might make it harder to get work into a branch for visibility. Could become more of a hinderance than anything else. Could this be checked in CI

**Comment by diversemix** [comment]
@jyenes / @damnhipster / @Cooryd 

Apologies for the not-so-well-thought-out ticket ... I've updated this ticket (totally my bad)

**Comment by hem-brahmbhatt** [comment]
I think it's useful to have this when running against PRs, rather than just on develop, where we'll then need to create another PR to fix develop. Having this run at the end of the tests should give us enough visibility and the chance to fix the coverage while giving us the opportunity to commit unfinished pieces of work.
