### ISSUE TITLE
Understand why we use Texture via pubsweet and directly

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#149]
`app/components/manuscript/Manuscript.js`
2:import TextureEditor from '@pubsweet/texture/TextureEditor'

and .... 

`client/texture/TextureEditor.js` 
import React from 'react'
import { TextureWebApp } from 'substance-texture'
....

**Comment by tamlyn** [comment]
Are you asking about the import from `@pubsweet/texture/TextureEditor`? This is an alias for the component in the `client` folder. It hasn't been contributed to PubSweet yet nor published to npm. But they are definitely interested which is why I built it as its own component from the off. 

Sorry, perhaps it would make more sense to name it something like `@elife/texture` until it gets moved to PubSweet.

**Comment by diversemix** [comment]
Ah ok... no that explains it... I thought it was installed twice. 

For things that are going to be adopted by pubsweet, (I'm thinking this might apply to more than texture) does it make sense to come up with another name `@pubsweetpending`

**Comment by tamlyn** [comment]
Good idea. See https://gitlab.coko.foundation/xpub/xpub-elife/merge_requests/68

**Comment by diversemix** [comment]
I'm happy with this - so closing.
