### ISSUE TITLE
Set up Greenkeeper (to ensure component/package versions are up to date)

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#150]
Prompted by the release of Texture preview 2 (https://github.com/substance/texture/releases) ... has prompted me to think how we deal with versioning / updating components within the product. It would be nice to think about how we should do this, alongside how we "pin" versions in package.json as well... then document :)

**Comment by giorgiosironi** [comment]
In general we lock package versions (how depends on the language platform: `npm-shrinkwrap`, `composer.lock`, Docker image sha-based tags) so that the output of `npm install`|`docker build` should be as reproducible as possible (some apt packages and anything you download can't be pinned as old versions get removed).

Then we have separate builds that try to update one (or more) dependencies and propose a pull request with the change:
https://alfred.elifesciences.org/job/dependencies/
The pull request gets reviewed by a human, and tests run on it like for any other pull request.
Some of these builds auto-merge like https://alfred.elifesciences.org/job/dependencies-elife-xpub-deployment-update-xpub/ rather than waiting for a human to review, optimizing for speed rather than for stability.

**Comment by tamlyn** [comment]
Yes. `yarn.lock` pins the dependencies. One nice side effect of moving the code to GitHub is we can start using https://greenkeeper.io which doesn't yet support GitLab. 

Or should Alfred handle that?

**Comment by giorgiosironi** [comment]
It's Node.js so we don't have specific tooling ready (most is for PHP/Python). Feel free to experiment with external services, I/Peter can setup stuff that needs wider permissions.

If you have scripts that are committed inside the repository, Alfred has infrastructure available to automate the "run and open a pull request" part.

**Comment by g-sam** [comment]
I move to change the title of this issue to 'set up Greenkeeper'

**Comment by diversemix** [comment]
sgtm

**Comment by tamlyn** [comment]
Monorepo support has just been merged https://github.com/greenkeeperio/greenkeeper-lockfile/issues/164

I don't have rights to add it to this repo myself but I have requested access.

**Comment by giorgiosironi** [comment]
Approved, and Github confirmed that with an email.

**Comment by tamlyn** [comment]
Thanks. I can see it in my dashboard now. If you log into Greenkeeper with Github I think you should see it too. Still needs setting up but a developer can do that, I think.

**Comment by hdrury1** [comment]
Can anyone update where we are on this? Ta muchly!

**Comment by tamlyn** [comment]
See #208.
