### ISSUE TITLE
Implementing ScienceBeam Feedback loop

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1528]
Whenever there is a change to the manuscript title log the change out (along with the manuscript id).
This will allow the logs to be parsed to generate a set of incorrectly extracted titles to train sciencebeam with.

I think this is the bear minimum - we could also store the extracted title in the database - that way we can maintain the history. 

/cc @de-code

**Comment by diversemix** [comment]
After talking with @de-code yesterday - we decided that the extraction and the changes to the title should end up in an S3 bucket.

I suggest we have a structure something like:
> `<s3-bucket>/sciencebeam/title/<manuscript id>`

Where the file is a CSV of datetime,title. The first entry being the extraction and subsequent entry being the tile on submission.

**Comment by de-code** [comment]
I am not sure which way is more convenient for you. The title could also be a column and it could just be an event log, e.g. with the following columns:

* `datetime` (although I love timestamps, i.e. with timezone information, not that it matters a lot for this use-case)
* `manuscript_id`
* `field_name` (e.g. `title` or `abstract`)
* `new_value`
* optionally: `old_value` (could be blank if it's the first value)
* optionally: `source` (e.g. `sciencebeam`, `user-edit`)

Maybe that could be even useful for other non-ScienceBeam related analysis.

But whichever method provides that information in an automated way (and is persistent) will work for me.

Just to provide some context how this is going to be used at my end:
* split manuscripts into separate datasets (to not test on training data)
* figure out new manuscripts and allocate them to one of the datasets
* generate GROBID training data based on CSVs and train GROBID (or any other model if necessary)
* update evaluation using new model
* Because the model changes over time, it will be useful to know what the actual extracted value was
* The most relevant value will probably be the last value within a certain time period, or the way xPub is currently used, probably the last value (as fundamental title changes probably happen within eJP for now or at full submission)

I hope that makes sense.

**Comment by de-code** [comment]
One thing that occurs to me glancing over the PR, is that I think we both thought of something different being the manuscript id. I thought of it being the 5-digit id, you probably the UUID.
I will somehow need to be able to link the two together.
I will also need access to the submitted document as well.

**Comment by de-code** [comment]
Assuming this is already deployed, how can I access it?

Any thoughts on my question regarding mapping to five digit manuscript id?
