### ISSUE TITLE
Need the ability to configure the TTL for JWT Tokens

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#160]
A Note for Peter:
If we are going to use JWT's in the email bridge and use PubSweet to generate those tokens then we will need to change the "time to live" (TTL) for that token - to ensure they do not last too long.

Currently this is set to 24 hours by PubSweet

**Comment by hdrury1** [comment]
@diversemix Can you translate please?

**Comment by jsms90** [comment]
It's a technical implementation detail that's part of the tasks associated with #196 I'm guessing that @diversemix has created this issue mostly as a reminder, rather than as a completely separate body of work. Would that be fair to say @diversemix?

But for the sake of curiosity, JWT (stands for JSON web token) and it's one method that's used for authorising users - allowing them to visit particular pages or to decide what content they should see on a given page.

How they ensure that you are who you say you are, etc is probably unnecessary to go into. But this analogy explains how they work & their purpose quite well, without going into technical details about how it's implemented:
> Think of it like a hotel key: you register at the front-desk, and they give you one of those plastic electronic keys with which you can access your room, the pool, and the garage, but you can't open other people's rooms or go into the manager's office. And, like a hotel key, when your stay has ended, you're simply left with a useless piece of plastic (i.e., the token doesn't do anything anymore after it's expired).

TTL = time to live, i.e. the time until your key code expires

@hdrury1 does that help?

**Comment by hdrury1** [comment]
No longer in scope.
