### ISSUE TITLE
User sees both interstitial pages.

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1652]
If you are already logged in to Journal then clicking "Submit My Research" should result in seeing only the Blue Page. However you do see both - this is slightly annoying but not a show stopper.

The fix will be within the Fastly CDN so @thewilkybarkid will need to get involved.

/cc @hdrury1

**Comment by hdrury1** [comment]
This is to do with the redirection logic we have in place, and the fact that logging out of xPub does not log the user out of Journal (so we have single sign on, but not single sign off). 

I would be interested to hear @chugginselifesciences and @gmaciocci input on this one from a Product point of view. Currently, from a user's point of view, it is impossible to sign out of xPub because the token from the Journal site persists (it's a long-lived, 12 month token which means signing into Journal once ensures you are logged in for a lengthy period of time). It was originally a Product req. that xPub would have a short-lived token (to secure multiple accounts on the same machine etc.) but this is currently a moot point because the Journal token persists.

I would suggest that we implement a single sign off pattern, so that signing out of xPub will also sign the user out of Journal (and vice versa), which would have the added benefit of preventing the user seeing the two interstitial pages.

Alternatively (@Cooryd can confirm?) we could rethink the logic of how the systems interact with each other but this will be the lengthier solution (and may not end up being possible).

**Comment by chris-huggins** [comment]
> I would suggest that we implement a single sign off pattern, so that signing out of xPub will also sign the user out of Journal (and vice versa), which would have the added benefit of preventing the user seeing the two interstitial pages.

Yes this is exactly what I would expect. In my opinion, logging out ant any time in xPub should log you out of journal and redirect to the journal home page.

This was the "first-use" scenario I put together to demonstrate the "before you start" page and "eJP redirect"
https://invis.io/P7RXVVZFNGC#/362491565_website-Not-Logged-In

**Comment by hdrury1** [comment]
Seems the solution to this will be to implement a single sign off pattern (ensuring that this also solves the bug of seeing both pages).

**Comment by chris-huggins** [comment]
Would this solve the bug where if a user is logged into the journal site they're still presented with the "log in with ORCID" welcome screen instead of the blue "continue" welcome screen? when they press "Submit my research"?

**Comment by hdrury1** [comment]
Hmm. I'm not sure. I'll raise another ticket for that bug regardless, and if this fixes all of those then whoop!

@giorgiosironi given that Chris is away could you be our go to person on the Journal side for implementing this?

**Comment by giorgiosironi** [comment]
Unsure of the scope of the solution. Redirecting to https://elifesciences.org/log-out after the xpub logout would log out the user from `journal` too. Can help spec whatever redirect dance we have in mind for this single sign off and then we can understand how complex that would be to implement and who should do it.

**Comment by hdrury1** [comment]
I'll set up a meeting next week to discuss, thanks @giorgiosironi

**Comment by hdrury1** [comment]
Blocked pending @giorgiosironi or @chugginselifesciences return.

**Comment by chris-huggins** [comment]
> Blocked pending @giorgiosironi or @chugginselifesciences return.

Do you mean @thewilkybarkid ?

**Comment by hdrury1** [comment]
Oops! Yes ;)

**Comment by hdrury1** [comment]
No longer blocked, as single sign out has now been implemented. Bug still seems to exist.

**Comment by erezmus** [comment]
@hdrury1 can this be closed?

**Comment by chris-huggins** [comment]
@erezmus I'm still experiencing this bug on login to reviewer

**Comment by erezmus** [comment]
hmm i thought this would be closed now that #1984 is fixed.

@hdrury1 @chugginselifesciences @giorgiosironi

**Comment by chris-huggins** [comment]
@erezmus @hdrury1 @giorgiosironi Apologies I just tried it again and worked this time so you're right I think this can be closed (but I'll leave to @hdrury1 in case)

**Comment by chris-huggins** [comment]
P.S. thanks to all involved as I've been looking forward to getting this one fixed
