### ISSUE TITLE
Manuscript title input should wrap/increase in height

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/elife-xpub#1667]
Currently some authors are missing extraction errors in their manuscript titles. The assumption is that they miss it because it's not shown/obscured because the manuscript title input is only tall enough to show one line of text.

It should instead wrap/grow to show the entire manuscript title, up to a maximum height in case of extraction errors... perhaps 3 lines of text tall?

![image](https://user-images.githubusercontent.com/41907215/54209257-5e295280-44d5-11e9-88a8-b7e04be33b63.png)

~The box should also allow rich text input: bold, italics, sub and superscript~

**Comment by petereast** [comment]
Following discussion, we've decided to push back on the rich text portion of this feature because it's likely to introduce issues and complexity wherever the title field of a `Submission` is used throughout the platform as we aren't always able to render the HTML generated by the rich text editor and showing raw HTML would be detrimental to the user experience.

**Comment by petereast** [comment]
Update: I've created a MR in pubsweet (https://gitlab.coko.foundation/pubsweet/pubsweet/merge_requests/546) that adds this component. I'm a little undecided as to how we proceed - do we add a copy of this component to `elife-xpub` or do we wait if/until it's included in pubsweet and block this ticket on the PS upgrade?

**Comment by hdrury1** [comment]
I'd prefer to add it to `elife-xpub` now, given we're unsure how long the upgrade will take.

**Comment by petereast** [comment]
Okay, I'll get a PR in after we've finished this meeting thing
