### ISSUE TITLE
Update selenium e2e tests to dismiss cookie notice

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1709]
Introduced with #1682 

Preventing e2e pipeline for passing.

**Comment by giorgiosironi** [comment]
Do the screenshots help? Available to help running it locally.

**Comment by thewilkybarkid** [comment]
Failure: https://alfred.elifesciences.org/job/test-elife-xpub/812/testReport/junit/(root)/test_xpub/test_initial_submission/

> selenium.common.exceptions.WebDriverException: Message: unknown error: Element is not clickable at point (392, 910). Other element would receive the click: &lt;div width="1" class="sc-bsbRJL sc-bnXvFD jTgmcH">...&lt;/div>

![spectrum test_xpub test_initial_submission-2019-03-19T16_36_40 295474](https://user-images.githubusercontent.com/1784740/54671561-0cdd1c80-4aee-11e9-8402-f8a5b454ce76.png)

**Comment by giorgiosironi** [comment]
Selenium by design always emulate what the user does, so if it can't click the element because there's something on top of it it will stop even if it's selectable through the DOM.

Dismissing the cookie notice (as soon as possible) is the right thing to do, but it needs a `except` so that if the cookie notice is not there it doesn't fail. This covers both backward compatibility and makes the test more robust to state.

**Comment by Cooryd** [comment]
selector for the button is: `data-test-id="cookieAcceptButton"`

**Comment by giorgiosironi** [comment]
Implementing with the `button[data-test-id="cookieAcceptButton"]` target.

**Comment by diversemix** [comment]
https://github.com/elifesciences/elife-spectrum/pull/166

**Comment by diversemix** [comment]
Fixed
