### ISSUE TITLE
Investigate Upload of submission 721667e6-ecd9-4859-b764-c9568e0f01a2

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1754]
There was a hotjar feedback on this stage with a sad face on the progress being stuck at 99%
see: https://insights.hotjar.com/sites/443270/feedback/responses/144171?frid=22599009

This could be related to  #1491 - this is still open as there have been a number of issues relating to this that have already been solved.

**Comment by diversemix** [comment]
Here are the logs:
[logs.zip](https://github.com/elifesciences/elife-xpub/files/3002871/logs.zip)

Notably the file did take a long time to upload:
```
 Manuscript Upload Time, Actual (627.405) , Predicted (124.60422928): 
```
taken from the log entry:
```
2019-03-23 06:07:31.986
{ json: { level: "info", message: "Manuscript Upload Time, Actual (627.405) , Predicted (124.60422928) | 721667e6-ecd9-4859-b764-c9568e0f01a2", timestamp: "2019-03-23T06:07:31.986Z" }, syslog: { severity: "Notice", appName: "elife-xpub", host: "prod--xpub.elifesciences.org", priority: "13", facility: "user-level messages", timestamp: "2019-03-23T06:07:32+00:00" } }
```

@hdrury1 I would recommend closing this as expected behaviour, but you (and @chugginselifesciences ) may wish to raise an issue to deal with the UX of this.

**Comment by hdrury1** [comment]
Yep. Not a bug in the system but definitely a potential opportunity identified for future improvement.

**Comment by hdrury1** [comment]
It's not 100% clear the problem any solution to this would be solving, since the user didn't leave any further feedback than a sad face. The assumption we are making is that the application currently appears broken to a user when it isn't, i.e. that it progresses to the 99% upload state and remains there until the file has finished uploading. 

Clarification: the upload progress is currently based on a prediction which takes into account a number of factors. If the prediction is hugely inaccurate, it means the upload progress fed back to the user is also inaccurate.

A better user experience may be 

1) to give a clearer indication of actual upload progress (@diversemix suggested we may be able to track how long it takes to upload 50% and then give a better prediction for the final 50%... this would improve the prediction)

and/or

2) offer the user more transparency, providing the user with messaging to indicate the different stages of upload (e.g. 'Uploading Manuscript', 'Saving Manuscript to S3', 'Extracting title' etc.)

Option 2) may be overkill at this point. Option 1), from my point of view, makes more sense.
