### ISSUE TITLE
Update 'Submit' validation text to include affected wizard steps

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1876]
Following on the work involved in #1875 it would be good to display additional feedback to the user upon clicking 'Submit' in the form of the wizard stepper, so they know exactly which pages the validation errors appear on and can navigate themselves back accordingly.

**Comment by chris-huggins** [comment]
I've tried to use relatively human language instead of just listing the options. Hopefully it doesn't introduce too much complexity.

If just one step has errors, I think we should just show the name within the text:

![image](https://user-images.githubusercontent.com/41907215/55550280-c253c680-56cf-11e9-8c84-ce993c8b9f9c.png)

If two, we should list them with "and" separating them:

![image](https://user-images.githubusercontent.com/41907215/55550323-db5c7780-56cf-11e9-87bd-bcbbf6655bf5.png)

If two or more, I'd like to separate with commas and use "and" for the last step:

![image](https://user-images.githubusercontent.com/41907215/55550408-0a72e900-56d0-11e9-8326-e90a2b63f037.png)

**Comment by Cooryd** [comment]
@chugginselifesciences 
I'm not sure if having two separated by an "and" reads well?

_"Please use the back button to review your "Files" and "Editors" and try again."_

/cc @hdrury1

**Comment by chris-huggins** [comment]
Yeah that's true, good spot. I changed the last bit then didn't proof it where there are more than one.

How about:
> "Please use the back button to review the "Author" and "Files" steps and try again."

Does the addition of "steps" help do you think?

Or we could go for:

> "Please use the back button to review the "Author" and "Files" steps before trying again."

The reason for using "and" is to avoid anything like:

>"Please review the following steps: Author, Files"

And I'm keen to include something about "trying again" although its still not that helpful as it doesn't instruct the user to return to the "Disclosure" page.

This sort of thing is more descriptive but a little long.

> "Please use the back button to review the "Author" and "Files" steps to check for errors and try submitting again."

I'm open to suggestions

**Comment by hdrury1** [comment]
I think

"We're sorry, but there appears to be one or more errors in your information that require attention before you can submit. Please use the back button to review the "Author" and "Files" steps before trying again."

would work.

**Comment by Cooryd** [comment]
Create PR https://github.com/elifesciences/elife-xpub/pull/new/1876-validation-text on monday once CI has woken up.
