### ISSUE TITLE
race condition in auto save

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1955]
When a user is performing a task that takes "some time" on the server - and when an autosave happens, this causes a race condition. The likelyhood of this being an issue is a function of the time it takes on the server and the frequency of the autosave.

This manifests itself as a number of errors in the logs:
- "Oops! There was a problem uploading your file"
-  "Any exception during `uploadManuscriptFile`"

Caused by not taking a lock on the manuscript object for updating. Also, should the autosave actually happen?

**Comment by erezmus** [comment]
The issue seems to be in the a flaw in the `save` method in the manuscript entity mode definition. The method checks the `updated` value with the one currently in the database and if its lower (i.e. the `updated` value of the model being saved is earlier than the stored one), then an integrity error is thrown.

In essence if between the time that we have fetched the manuscript from the database and saved it, another save on the same manuscript model happens, then the error will be thrown.

```
// 1. fetch manuscript
let manuscript = await ManuscriptModel.find(manuscriptId, this.userId)

// 2. do some operation
operation()

// 3. save manuscript
await manuscript.save()
```

if in between 1 and 3, the autosave operation runs and completes (and thereby updated the `updated` value), then when 3. happens the `manuscript.updated` value will be before the one updated by the autosave and will throw the integrity error.

This also seems to be a problem in the pubsweet base-model `save` method
