### ISSUE TITLE
Checkbox re-checking on Details page

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1961]
**Steps To Reproduce**
1. Begin a new submission
2. Navigate to Details page
3. Check 'This manuscript has been discussed with an eLife editor'
4. Attempt to navigate past the page
5. Observe validation error
6. Uncheck checkbox
7. Navigate forward
8. Navigate backward
9. Observe checkbox has rechecked

**Expected behavior**
Checkbox should remain unchecked!

**Screenshots**
<img width="886" alt="Screenshot 2019-04-30 at 10 04 22" src="https://user-images.githubusercontent.com/17023702/56951304-5aa66500-6b2f-11e9-8446-ea8b2b883e83.png">

**Device, Operating System and Browser**
Macbook Pro, Chrome version 73

**Comment by erezmus** [comment]
The issue seems to be that the Manuscript model's `save` method is not updating the `previouslyDiscussed` column when the value is `null`.

I've tracked down the problem to the following code in the manuscript model definition (`packages/component-model-manuscript/entities/manuscript/index.js`) at the constructor:

```
constructor(props) {
  super(lodash.merge({}, emptyManuscript, props))
}
```

This initialises any new Manuscript models to the default values that are not set in `props`.

To see why this is a problem in this case, we need to see what happens when we save the Manuscript model. The Manuscript model's `save` method overrides pubsweet's `BaseModel.save` and calls the Objection method `upsertGraphAndFetch`.

Digging deeper inside the mechanics, it seems that the operation creates an UpsertGraph object. In `lib/queryBuilder/operations/UpsertGraphOperation.js`:

```
onBefore1(builder) {
    this.graph = new UpsertGraph(this.models, this.isArray, this.upsertOpt);

    return this.graph.build(builder).then(() => this.delete(builder));
}
```

The UpsertGraph, as its name implies builds a graph of all related models to be saved. Each node has an `upsertModel` property which is the model to be updated and an `currentModel` property.

When it builds a graph it only fetches the model ids but it does it by running a query which calls the constructor of the models (see `createModels` method in `lib/queryBuilder/QueryBuilder.js`). Since the Manuscript's Model constructor sets empty values, the UpsertGraph's node for the manuscript has a full empty ManuscriptModel with only its id set. When the patching gets executed, since the default value for `previouslyDiscussed` is set to `null` in the node's `currentModel` and the same in the node's `upsertModel`, then the column doesn't get udpated.

In essence the UpsertGraph has an incorrect view of the current state of the Manuscript due to the fact that it uses the constructor in patch operations.

The presence of this constructor will affect any patch operation done on Manuscript models. I tested this with a simple patch call:
```
await ManuscriptModel.query().findById(id).patch({previouslyDiscussed: 'foo'})
```

The database logs on execution of the line above generates a full updated query of all the table columns instead of just updating the `previously_discussed` column.

**Comment by diversemix** [comment]
Great work on this thanks @erezmus ... are we confident we are not using constructors for other models?

**Comment by erezmus** [comment]
After more digging i think it only occurs if you have a constructor and use upsertGraphAndFetch. File and User entities use `upsertGraphAndFetch` but don't seem to use default values in constructor.

I've added a bug report with a link to a bug POC repo i coded up: https://github.com/Vincit/objection.js/issues/1333
