### ISSUE TITLE
Validation on suggested reviewers not working

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1972]
**Describe the bug**
A user was able to enter only names of reviewers and not emails, before proceeding to the next page of the wizard. 
Upon reaching the confirm dialog, they were unable to complete the submission because the application threw a GraphQL error.

<img width="514" alt="Screenshot 2019-05-02 at 09 42 45" src="https://user-images.githubusercontent.com/17023702/57064601-ac312a00-6cbe-11e9-84a6-1e69661313d3.png">

**Expected behavior**
User should not be able to enter a reviewer name without an email and vice versa. Previous validation rules should be re-applied.

When entering a value into either input in a given row, the `(Optional)` tag should be dropped from both inputs.

**Known submissions affected by this bug**
`de57834a-f39e-4f67-92a6-61d9896f40b2`
`13d414db-82b7-49ed-8998-ed2cb90b6aed`

**Comment by chris-huggins** [comment]
@hdrury1 It's occurred to me that we show both the name and email inputs with `(optional)` in the label. This sort of implies you can fill in just the name without an email address, which isn't correct (assuming we fix this bug).

Once we fix this bug I wonder if we should add `(optional` to the "Suggest reviewers" heading instead of each label, or look at a different pattern to show each reviewer is optional, but if adding a reviewer we must have the name and email address.

The recent issue mentioned by Susanna also made me wonder if we should be asking for the institution of each reviewer?

**Comment by hdrury1** [comment]
@chugginselifesciences My understanding is that (optional) should disappear as soon as you start typing anywhere in a given row... so as soon as you type a reviewer's name, the email is then no longer `(Optional)`
