### ISSUE TITLE
File uploads state error

### ISSUE THREAD

**Issue by petereast** [elifesciences/elife-xpub#1983]
**Describe the bug**
This bug is in the file upload, where the user is able to reset the view of the manuscript upload component while the upload state is still invalid, thus preventing the user from continuing with their submission.

**Steps To Reproduce**
> Tested in browserstack, IE11 on Windows 7
- Begin a submission as usual
- Upload a valid `.pdf` file with the **manuscript uploader**
- Upload some other supporting files
- Click the <kbd>Replace</kbd> button in the **manuscript uploader** and upload an invalid file
- The file uploader now resets to it's inital state, no validation error is shown and the user is not able to continue with their submission.

**Expected behavior**
We would expect the manuscript uploader to show a validation error when the user uploads an invalid file.

**Screenshots**
https://insights.hotjar.com/r?site=443270&recording=2157748852&token=4526ed09fc106792b1e5793ab569342a

**Device, Operating System and Browser**
All browsers

**Comment by erezmus** [comment]
Issue is two fold:
- When uploading a file with incorrect extension the request doesn't have multipart/form-data set in its headers, hence it gets ignored by the apollo upload express middleware that is used for file uploads, the request then seems to fail as the file upload is not processed for consumption by the resolvers.
- At the client level, the validation checks whether we have a single file in the manuscript but we don't check its type. This needs to be modified so that we check that we have at least one file with type manuscript.

**Comment by hdrury1** [comment]
It's worth noting too @erezmus that when in this state, the link to remove all supporting files disappears too:

<img width="960" alt="Screen Shot 2019-05-17 at 12 29 47" src="https://user-images.githubusercontent.com/17023702/57925263-949d9800-789f-11e9-9d42-cd78538e9ea5.png">

**Comment by erezmus** [comment]
@hdrury1 So i had a look at fixing that. Currently the code checks whether you have manuscript uploaded and if you don't have one, it doesn't display the <kbd>Remove All</kbd> and the <kbd>Add More supporting files</kbd> buttons.

Now that we are checking as part of this fix whether there is a manuscript at validation step, maybe we can drop this check? If so then I can add a separate ticket.

cc @chugginselifesciences

**Comment by chris-huggins** [comment]
As long as there's a supporting file present we should show the `Remove all` and `Add more supporting files` options. Even if the manuscript has been re-uploaded. But the situation in the screenshot above is a result of this bug I assume? It shouldn't be possible to have no manuscript uploaded but have supporting files added.

@hdrury1 and I have discussed making the supporting files option always visible (with some explanation text to try to inform users on what we want them to upload/avoid them uploading "everything".

If we're having issues with how/when we show or hide the supporting files options maybe we should make this change now to solve these issues, instead of fixing bugs then changing it again soon after?

![image](https://user-images.githubusercontent.com/41907215/57931107-a1c28300-78af-11e9-95ab-696fa79ee34e.png)

**Comment by hdrury1** [comment]
Chris has a point, but given the above work is likely to be some way off I still say we attempt to fix the bug now.

@erezmus the 'Remove All' should appear if there is a supporting file uploaded, so the code should check against this (rather than the presence of a manuscript).

**Comment by erezmus** [comment]
@hdrury1 i think this should go as a separate ticket as we might need to update tests...

**Comment by chris-huggins** [comment]
@hdrury1 no problem. I just spoke to Erez, but noting here for reference. Another thing we should be aware of is the `Add more supporting files` text. Currently I think it always says "Add more supporting files" which is [incorrect](https://github.com/elifesciences/elife-xpub/issues/1933). This should also always be shown if there is a supporting file, but is more complex:

- it should be hidden when no file is uploaded
- it should say "add supporting files" when the manuscript is uploaded
- it should say "Add more supporting files" if one or more files are already present
- If the user does anything else to the manuscript file, it doesn't matter. If there are supporting files it should say "Add more supporting files"
- if the user presses "remove all" it should say "add supporting files" again. It should never be removed entirely as the file upload target should never return to an "upload" state - it should either have a manuscript of be in an error state.
