### ISSUE TITLE
Implement single sign out pattern

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#2020]
When a user logs out of Libero Reviewer they should be also logged out of Journal.

Logging out of Libero Reviewer should redirect the user to Journal home.

Hopefully this will solve some of the bugs we have been seeing with regards the different login screens and logging out in general (#1652 and #1904) but we should aim to implement this pattern first before tackling any remaining bugs.

**Comment by diversemix** [comment]
@hdrury1 I would like to know why we are doing this. For example, if we sign into medium with our google credentials - signing out of medium does not sign us out google (nor should it).

I have a suspicion (if I assume the reason we are doing this is not to re-login automatically) that we do not invalidate the Journal's token (in xpub) as its a long lived token. This is perhaps what we should be doing rather than signing out of Journal. Of course I could be wrong - still have jet lag :/

**Comment by hdrury1** [comment]
Thanks for the input @diversemix. We had a discussion and determined this would be the least risky, most straightforward way of implementing the product requirements. Logging out of Reviewer will redirect to Journal (in a logged out state) so UX is consistent.
