### ISSUE TITLE
create corresponding author email & associated "thank you" pages (Confirm & Deny)

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#204]
When the corresponding author is not the submitter, they are sent an email (#154).

This email should contain a link that allows the recipient to verify that they are indeed the corresponding author.

## Questions
- does the email contain any part of the manuscript or is it just a call to click on the link?
- does clicking on the link implicitly verify the author or is there a further action required to explicitly confirm?
- does the author have a chance to review the manuscript before confirming?
- does the recipient have an opportunity to assert that they are *not* the author?
- how is the email bridge (#196) used to enable this feature?

**Comment by hdrury1** [comment]
We've had a problem with spam-bots in the past, in that they have clicked on a link within an email to verify whether or not the email is spam, without the intended recepient even opening the message. This has led to, for example, reviewers 'accepting' review invitations without actually reading them and had resulted in us having to introduce a two-step process (reviewer clicks link to access application, then clicks second link to agree to review). Can we avoid this eventuality? From a product perspective I would rather a corresponding author be able to confirm straight from the verification email, without having to ever interact with the application. Assuming we can do this, below are product requirements for this feature.

Product requirements: 

1. User receives an email notification informing them they have been listed as a corresponding author. This email contains the title of the manuscript and the name of the submitter.

2. User clicks a button embedded within the email to confirm he is the corresponding author, and this takes him to a 'Thank You' page.

3. From this page, the User has the option to log in to the system, at which point the submission will be reconciled with his account and appear on his dashboard.

4. Reagrdless of whether or not the user logs in, the verification ribbon should be removed from the submission and the validation message for this field changed to a green 'Verified'.

5. If the User is _not_ the corresponding author, he clicks a second button embedded within the email. He is taken to another Thank You page and given the option to undo this action by clicking the 'Made a Mistake?' button. Clicking this button will redirect to the page referred to in (1) where he can log in.

Designs:

[Email to be received by corresponding author](https://github.com/elifesciences/elife-xpub/files/2105192/corresponding-author-email.pdf)

[Confirmation screen](https://user-images.githubusercontent.com/17023702/41456174-8b2d6a60-7077-11e8-86bd-dc20bd7e6533.png)

[Decline screen](https://user-images.githubusercontent.com/17023702/41456190-958a838a-7077-11e8-8617-1540504485d5.png)

**Comment by jsms90** [comment]
@hdrury1 I appreciate that @NickDuf's time is limited, so this may not be possible. But is there any way we could get these new designs into invision so that they can be commented on, same as we've been doing for the other designs? :pray:

**Comment by jsms90** [comment]
@hdrury1 I gather that you and @g-sam spoke about these product requirements at standup yesterday? Can I confirm that you have decided on a one-click process for users (despite potential potential spam-bots) vs making a user go through a two-click process?

We're assuming that, by "spam-bots", you mean non-malicious bots that crawl your email to try and ascertain whether the contents is spam or not? One solution would be to keep the one-click & allow these spam bots to crawl at first. Then look at the info on where these requests are coming from & guard against the user agents associated with the bots - i.e. not follow through with the usual behaviour, if the user agent is deemed to be one of these bots.

The down side of this is that we would be allowing bots to operate at first, in order to learn about them, which means accepting a certain amount of false confirmations (at the beginning).

**Comment by jsms90** [comment]
Yesterday @damnhipster were attempting to break the rest of this ticket into smaller chunks.

### Background
In the current PR against this issue, I've already done:
- Create both Thank you pages (without styling)
- Create email template, including links that connect to the Thank you pages
- Generate a JWT token & put this in the "Confirm" link

Still to be done:
- Finish token verification process - verify token when author is redirected to xpub from their email
- Mutate the manuscript's corresponding author object
- Connect the corresponding author's confirm/deny state, to the show/hide of the notification ribbon
- Handle unhappy paths i.e. show error pages if/when token is invalid

### New scope of this ticket
I'm planning to remove token generation from the existing PR, so that the scope of this ticket is limited to:
- [ ] Creation of Corresponding Author Confirmation page - designs above + slight change, to conform to [these new requirements](https://github.com/elifesciences/elife-xpub/issues/298#issuecomment-402432658)
- [ ] Creation of Corresponding Author Deny page - see designs above
- [ ] Email contents matches link above (designs pending?). Should contain: name of submitter, name of corresponding author, manuscript title + Confirm & Decline links

And I'll open an issue for each of the other steps.

**Comment by diversemix** [comment]
Looks a good breakdown - don't be afraid to create as many tickets as needed :+1:

**Comment by hdrury1** [comment]
New wording for the confirmation page: 

[email-confirmation-screen 2x](https://user-images.githubusercontent.com/17023702/42327368-733f570a-8063-11e8-92bd-34fe7858a3d0.png)

**Comment by jsms90** [comment]
Also just want to detail the potential implementations we discussed, what we decided on & why.

### Storing Corresponding Author's confirmation state
When a user clicks on a link from their email (Confirm or Decline), this needs to cause a graphql mutation - changing corresponding author's confirmation status

Here are the possible states that we need to account for:
- pending - when author has yet to answer email
- confirmed
- declined

@tamlyn has altered the added this to our GraphQL definitions:
`manuscript`(Object) - `AuthorMetadata`(Object) - `confirmed`(Boolean)

Confirmed/Declined state: true/false boolean
Pending state: AuthorMetadata object is removed

But this representation doesn't allow for the journey where an author clicks "Decline" & then "Made a mistake".

Decision: TBC

### How GraphQL mutation will be called - from server or client?
When an author clicks on "Confirm"/"Decline" from their email, this needs to cause a GraphQL mutation. How can we do this?
1. Embed GraphQL mutation in email link
1. Email link sends GET request directly to a REST endpoint on our server, which is then responsible for triggering a GraphQL mutation & serving the appropriate React page (Confirm/Deny page if mutation was successful / error page if unsuccessful e.g. token is invalid)
1. Email link redirects author straight to our Confirm/Deny page & these React components are responsible for firing off the GraphQL mutation

(1) is not technically possible, so it's between (2) - server-side entry & (3) - client-side entry


- client-side
    - disadvantages
        - need to create custom loading state (cannot serve "Thank you" until mutation has actually been successful)
        - error handling
    - advantages
        - calling graphql mutations from client side is consistent with the rest of our application

- server-side
     - disadvantages
            - error handling
            - would need to add new architecture to app - REST endpoint & calling graphql from server-side
        advantages
            no custom loading state

**Decision**: (2) client-side for consistency & therefore simplicity of codebase + loading screens will need to be designed for other areas of our app anyway

### How to check validity of token
We can generate a unique token and attach this to the email, then check whether the token is valid, before altering the data in the database.

But how do we validate that token? 
1. Save tokens associated with a manuscript in the database. When an author navigates to a Thank you page with this token, validate this token by checking that it is in the database against that manuscript
1. Store the email address inside a JWT. Validate that this is the Corresponding Author by checking whether this is the email address listed against the manuscript.

**Decision:** (2) - no need to store tokens in DB :smile:

**Comment by jsms90** [comment]
@hdrury1 As a PA (submitter who is not the corresponding author),
- I fill in wizard step 1, including the corresponding author email address aaa@bbb.com
- I click next
- an email is sent to aaa@bbb.com

**Note: I have not yet filled in step 3, which contains the manuscript title.**

But the email template & Thank you page designs all assume that the manuscript title has already been entered.

---

I'm wondering whether it would be advisable to send this email to the corresponding author on Submit instead - at the end of step 4?

Multiple reasons for this:
- More intuitive for the PA
    - As a PA, you might see the notification ribbon & assume that you cannot submit until the corresponding author has verified their email address and the ribbon disappears
    - As a PA, nothing in the designs suggests that filling out the input field on page 1 will cause an email to be sent to the corresponding author. They may want to know that they're going to trigger this action, before it happens?
- A corresponding author's verification of their email address has no bearing on submission. Since submission can continue without them seeing or acting on the email, is there any pressing need for them to receive this email beforehand?

Is there anything I'm not considering here?

Thoughts?

**Comment by jsms90** [comment]
The current version of the email uses the name of corresponding author (first name & last name) but doesn't contain the name of submitter, which is in the requirements.

This is because we do not currently fetch the logged in user's name from Orcid unless they click 'Pre fill my details'.

In order to complete this part of the requirements, we first need to fetch the user's login details from Orcid, as soon as they click 'Submit a Manuscript' - opened a new issue #309

**Comment by tamlyn** [comment]
Are we sure that JWTs support the product requirements? e.g. JWTs have a set period of validity (usually a few hours) but can be used any number of times in that period and cannot be revoked*. In contrast a token stored in the database can be removed on first use or for any other reason. As a result it's validity can be longer. 

It may be that this limitation is not an issue but it's worth thinking about now before we build the email bridge functionality on it.

* You could store a list of black listed JWTs but then why not just store the valid ones instead?

**Comment by hdrury1** [comment]
@jsms90 Agree that corresponding author should be emailed on submit- an excellent point was raised that if the submitter never completes a submission the corresponding author should not be contacted.

**Comment by jsms90** [comment]
Yeah very good point @tamlyn. I'm going to suggest that this issue is not ready to be broken out into technical sub-issues because the breakdown that I've suggested above assumes that we have decided to use JWTs. If we're going to store tokens in the database, then we need to think about how this will be represented in our data model & we'll probably need another ticket or 2.

We'll need to make the technical decisions listed [in this comment above](https://github.com/elifesciences/elife-xpub/issues/204#issuecomment-402741052), before breaking down this ticket.

In the meantime, we need to change our existing codebase to come into line with the new product requirements:
- remove the notification ribbon from the wizard & the `confirmed` state on the authorMetaData
- stop sending emails when a user clicks Next on page 1

As the email verification isn't as high a priority as fixing the e2e tests or implementing the layout designs, I suggest that we complete the changes above & then bench further work on this feature until after our demo?

**Comment by damnhipster** [comment]
@tamlyn JWTs would only be used for an operation with a limited scope (verifying the corresponding author), so the damage that can be done by the tokens being compromised is low.

You're correct in saying that we cannot revoke access using JWT, but we can control the logic ourselves to handle cases where the operation is called multiple times.

**Comment by diversemix** [comment]
@hdrury1 is this still applicable?
