### ISSUE TITLE
Click handlers very slow in People Picker

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#2194]
Interaction with the People Picker is slow in production across a multitude of browsers (Brave, Chrome, Firefox)

I'm getting the following in the inspector (Brave):

![Screenshot 2019-06-26 at 15 47 31](https://user-images.githubusercontent.com/17023702/60189965-bd636680-9829-11e9-8178-4a2d919e5952.png)

**Comment by erezmus** [comment]
looks like its re rendering the whole people picker on every click?

![Screenshot 2019-06-27 at 15 49 29](https://user-images.githubusercontent.com/2045191/60276289-38dd1a80-98f3-11e9-999a-99f6c64bc5c2.jpg)

**Comment by erezmus** [comment]
Reproduced violation locally using the production api, going to have a look at this library as per @Cooryd 's suggestion on windowing:

https://react-window.now.sh/#/examples/list/fixed-size

**Comment by erezmus** [comment]
Changed course after thinking about it about more, managed to prevent unnecessary re renders with a shouldComponentUpdate lifecycle hook. Still getting violations when reaching the reviewer limit, though

**Comment by erezmus** [comment]
After further digging, its not possible to stop rerendering when reaching the limit of editors as the `isSelectButtonClickable` prop gets updated for all components. Since it won't happen very often, it will have to do for now, but if it does become a problem, we'll need to use the aforementioned windowing solution
