### ISSUE TITLE
Update Radio atom to conform to the styleguide

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#222]
The Radio atom should look like the one in the [styleguide](https://projects.invisionapp.com/share/NZKXOQUV4P3#/screens/302926985).

Right now we don't use any Radio component, but there is one in [pubsweet](https://gitlab.coko.foundation/pubsweet/pubsweet/blob/master/packages/ui/src/atoms/Radio.js). If updating that component to look like the one in the styleguide via theme variables is not possible, then we should create our own Radio atom (e.g. in `app/components/ui/atoms`).

**Comment by jsms90** [comment]
Since we don't currently have any designs where radio buttons are used, is it really necessary or wise to create this right now?

If/when a radio button does become part of the designs for our app, we may find that designs change after seeing it in a specific context. Think of the first 6 months that were spent on this project, creating components within pubsweet, before knowing the context in which they were going to be used.

In general, I would caution us against creating components that are not yet being used in our application. What if they are never used? Then we are just creating bloat for no reason.

Any work that goes into this component is work that is not demo-able. I suggest that, if this issue needs to remain open at all, it be put in our backlog until such a time as we need a radio button in our app?

**Comment by hdrury1** [comment]
Closing down until we have a need for a radio button.
