### ISSUE TITLE
Update progress indicator to reflect product requirements and styling

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#224]
The styling of the progress indicator component should match the [styleguide](https://projects.invisionapp.com/share/NZKXOQUV4P3#/screens/302926985).

Product requirements:

- The indicator should update to reflect the user's progression through the submission wizard. 
- Each page completed without validation errors should be indicated with a filled circle and tick mark.
- Each incomplete page should be indicated with a furniture colour circle.
- The current page should be indicated with an unfilled circle outlined in the primary colour and the step number in text colour.
- A step is not considered complete until a user has hit the 'Next' button and received no page validation errors.
- If a user navigates back through the wizard using the 'Back' button, previously completed steps should still be recorded by the progress indicator.

**Comment by jsms90** [comment]
@hdrury1 at one of the most recent meetings, it became apparent that a user is supposed to be able to click on a circle in order to navigate to different points in the wizard. So this component actually needs to have more functionality than currently exists.

I suggest that we consider this component to be a feature in its own right & turn this issue into a fully-fledged feature issue, including all the necessary product requirements. Then, styling will be just one aspect of completing the feature.

It makes little sense to start working on the styling, before we have added all the functionality. This is because, as you start building out the functionality for a component, the structure (HTML) may need to change. If the structure changes, then the styling needs to change accordingly.  So working on styling before functionality can actually cause duplicated effort.

Does that make sense?

**Comment by hdrury1** [comment]
@jsms90 Agreed. I will go ahead and update the title/description to reflect this.

**Comment by jsms90** [comment]
@hdrury1 What happens if/when a user has half filled in the page that they're currently on (e.g. page 3) & then they try to navigate backwards to the previous page (page 2)?

Does the page 3 remain half completed? Or is the user prevented from navigating backwards because all the fields are not yet "valid"?

**Comment by jsms90** [comment]
Just to be clear, for when @g-sam & @tamlyn return, the requirements are being updated because it's no longer deemed necessary for the progress bar to be clickable for navigation purposes. The thinking is that it will come up during user testing, if it's a problem? Is that correct, @hdrury1? :+1:
