### ISSUE TITLE
Create a Notification Ribbon component (functionality to be added)

### ISSUE THREAD

**Issue by mihaildu** [elifesciences/elife-xpub#228]
**User Story:**

_As a submitter I want a notification ribbon in order to know whether or not the corresponding author has accepted their responsibility._

**Product requirements/Acceptance criteria:**

Functional:

- When the submitter edits the email in the field on page 1 of the submission wizard and it no longer matches the email associated with the submitter's ORCiD account, a ribbon is displayed at the top of the page after the submitter hits 'Next'.
- This ribbon remains at the top of every page of the wizard until the corresponding author takes an action to validate themselves as such.
- The submitter can use the 'resend' link within the ribbon to send another validation email to the nominated corresponding author.
- If the submitter resends the validation email, the ribbon updates to indicate this.
- The presence of the ribbon should not stop the aubmitter from completing the wizard.

**Relevant links to design(s):**

[Invision Prototype](https://invis.io/CDLI0R5KBF6)
[Styleguide](https://projects.invisionapp.com/share/NZKXOQUV4P3#/)

**Tasks**
- [x] Create notification component - suggested that this be placed in `atoms`

**Comment by jsms90** [comment]
@hdrury1 Could you change this to a feature issue, detailing the user story & product requirements?

After all, this is not just a styling issue, but an issue for creating a whole new component, with associated functionality from issue #53

**Comment by hdrury1** [comment]
Editing the title and description to reflect a feature.

**Comment by hdrury1** [comment]
@dryhten I've removed the email bridge task, as this is beyond the scope of this feature. For now let's stick to the functionality of having a corresponding author verify themselves as such. This is going to require an email token being generated and embedded in the verification email.

**Comment by hdrury1** [comment]
Maybe we split this issue to account for the actual component that has been made already and the functionality that is still to be implemented?

**Comment by dryhten** [comment]
@hdrury1 I don't mind either way. When I created this issue I had in mind only the last task. If you want better modularity I suggest we keep "doing the notification ribbon component" here and move the functional part to a different issue, so we can close this one before I'm off next week.

**Comment by jsms90** [comment]
Yeah sorry guys, I probably confused things here.

My [suggestion above](https://github.com/elifesciences/elife-xpub/issues/228#issuecomment-398725956) was that a new issue get created - a feature issue (user story + requirements + list of sub tasks), to try and help @hdrury1 have a greater overview of what has/hasn't been done yet & how far away a feature was from being finished.

At our last retro, we decided to use milestones to group all the sub-tasks associated with a feature. Since the retro, we canned that idea, in favour of using issues instead. This is where the feature issue template has come from.

But neither milestones nor "feature issues" are going to be used for grouping issues together into features, I think we might as well get rid of our "feature issue" template.
