### ISSUE TITLE
Investigate npm packages for RBAC

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#2325]
Roles based access control is as old as the hills - let's use something out there already.

We need to have a configurable way of defining access control in the application - the requirement is that the Editorial Team can now edit submissions too. It should also store the configuration in a database.

/cc @hdrury1

**Comment by diversemix** [comment]
This looks pretty good: https://www.npmjs.com/package/accesscontrol

**Comment by diversemix** [comment]
If using `nestjs` then they use `guards` ... https://docs.nestjs.com/guards

**Comment by diversemix** [comment]
Ok, investigating more using `guards` (in the documentation example) has the issue that the operations are protected with roles hard-coded at run time. Talking with @chugginselifesciences ... we need to support dynamic teams (roles) with dynamic permissions. 

Therefore, I suggest we use a "guard" approach, to that we can protect Queries and Mutations  - and in addition use something like https://www.npmjs.com/package/accesscontrol so we can store teams and permissions in the database. However this package does not give us mulitple roles per user, to the guard that we would author would need to account for enumerating over the roles of the user to look for the required permission for that operation.

**Comment by jure** [comment]
:wave: We've looked at the options out there when designing PubSweet's authorization system, and there really wasn't anything out there that would have the level of flexibility needed for publishing workflows (as you say, dynamic permissions, ones that depend on state). So we built `authsome` (it's very minimal), and paired it with teams (linked to objects or global) and their members, for a complete approach. As an example of an `authsome` mode with dynamic permission, take a look at Hindawi's: https://gitlab.com/hindawi/xpub/xpub-review/blob/develop/packages/app/config/authsome-mode.js

When it comes down to it, most of these systems are very similar, but perhaps the nomenclature differs from one to the other. Having things be this dynamic though is not a usual requirement, so not a lot of systems will address it from the get go.

I'm interested in hearing what features you're looking for when evaluating these packages, so that I can perhaps get a better sense of where we can improve `authsome`.

**Comment by diversemix** [comment]
@jure ... when I talk about it being dynamic - I mean data-driven, i.e. you don't need to change any code to change the way things work. `accesscontrol` allow for this

**Comment by jure** [comment]
Yes, exactly. What you’re describing amounts to an ABAC, which is what both `authsome` and `accesscontrol` implement.
An example of this “data-driving” is e.g. https://gitlab.com/hindawi/xpub/xpub-review/blob/develop/packages/app/config/authsome-mode.js#L170, where the manuscript’s status determines the permissions.

In the big picture, the combination of teams, their members, and the state of the objects that teams are linked to, determines permissions.

It would be good to know where `accesscontrol` is more dynamic, so that we can evaluate the need for that in PubSweet!

**Comment by diversemix** [comment]
Talking with the wider Libero team here ... it makes no sense for us to have it as part of Libero Reviewer per-se. Current thinking is It should be a shared service across all the Libero suite. 

/cc @BlueReZZ @GiancarloFusiello @gmaciocci

**Comment by GiancarloFusiello** [comment]
> Talking with the wider Libero team here ... it makes no sense for us to have it as part of Libero Reviewer per-se. Current thinking is It should be a shared service across all the Libero suite.

This could be a separate project with its own domain that all other projects requiring authorisation can utilise. Commence project Libero Authoriser 😄

**Comment by chris-huggins** [comment]
In future we'll need a UI to allow journals and multi-tenancy journal owners to manage teams, team members and permissions across the Libero product range so this makes sense to me. Google groups is probably a reasonable (if dated) example of what we might need.

https://groups.google.com/a/elifesciences.org/forum/#!forumsearch/

**Comment by diversemix** [comment]
@GiancarloFusiello ... I don't think it makes sense as a separate project as it doesn't take much to think the same for .... auditing, storage, workflow .... all these cross-cutting concerns should really be common and if we are talking DDD in some sort of shared-kernel.
