### ISSUE TITLE
Investigate how we prevent editor/author contention on a submission

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#2326]
When we come to do the editorial pages then we can potentially have a conflict between the editor and the author updating the submission. We need answer: 

- Do we want a locking mechanism? This has the potential of staying locked (like editoria)
- Do we want to allow the conflict and have last-write wins? Would this mean re-doing auto-save?
- I'm thinking that doing the above with some sort of warning banner that someone else has this open may be the best compromise?

/cc @hdrury1 / @chugginselifesciences

**Comment by chris-huggins** [comment]
My general thinking on this is that it's best to simply show what's happening to help make people make judgements, instead of trying to lock/open and then design for various potential edge cases and problems to override (e.g. if somebody has taken control on a submission but gone on holiday).

Therefore, we should clearly show when the author or other staff users are looking at their submission (i.e. simply have it open while logged in) to help users judge whether or not they should make changes or whether they risk conflict. Worth noting we would not show to authors when staff or Editors are looking at their submission.

The way we handle the overall workflow between staff and authors should define where the author can edit or not as we want to prevent authors changing things that have already been checked. e.g. an author can only change something at initial QC stage when Ed Office staff have added a comment to request an update.

We want to enable a team of staff to work on multiple submissions together, so clearly showing if a colleague is working on a submission will help make that judgement, without the need to "assign" or "check in/out" submissions to individuals.

However, this doesn't apply within the wizard. The conversations had so far on the Product team have concluded that we will expect staff to manage conflicts with authors by telling them not to make changes, instead of designing or building in this sort of feedback into the wizard. As we scale, we might find that we need to include something like a banner in the wizard to feedback to authors if changes are being made by staff to avoid them making conflicting changes. But we should wait to see if this is necessary in practice.

In summary:

- We should avoid "locking" submissions in general
- We would expect staff to ask authors not to make conflicting changes when supporting them with changes to their submissions via the wizard (i.e. before submission)
- If there are conflicts "last-write wins" makes sense unless it causes technical problems
- If it is difficult we can explore other options... e.g. you asked above if we need to re-do auto-save?
- We will see how we get on to decide if a banner is necessary - it's a good option if needed
- Looking further forward we would need a "web socket style mechanism" to show staff when other staff, editors or the author are "looking" at the submission to help them judge whether to make changes or not
- This is to avoid complex locking/unlocking/assigning/hiding behaviour in future when multiple people or teams are working on a submission (e.g. how Production work on Kriya)

I'll try to gather some examples as it's generally a well solved problem

**Comment by diversemix** [comment]
My suggestion then is to cover the case where a user has asked for help on their submission but left their browser open (thus auto-saving). 

We should flag and prevent the staff (or user) from editing this submission until there has been no auto-save (`updated` time is older than 10sec). 

/cc @hdrury1 @Cooryd @will-byrne

**Comment by chris-huggins** [comment]
@diversemix We should avoid locking/preventing staff making changes whenever possible. I agree that we should indicate on the staff dashboard when the author has their submission open, and should show on the staff submission detail view (tabs). But if the author has it open too we should see if we can find a way for staff/editors to lock out the author (or just force returning them to the dashboard) to avoid conflict. Staff should always have control and never be locked out or prevented from taking action.

**Comment by hdrury1** [comment]
@chugginselifesciences we're looking for a quick and dirty solution to this right now in order for us to enable staff to access submissions in the current production system as soon as possible (and knowing that the whole application will be superseded by Libero Reviewer).

We can then think about something more elegant along the lines of your suggestion for Libero Reviewer.

@diversemix I presume your method would involve staff contacting the author and asking them to manually close their browser?

**Comment by diversemix** [comment]
@hdrury1 yes... My worry is that if we do anything more - it will take more time and given its all 'throw away' development

@chugginselifesciences  I'm keen not to sink any more effort than needed into this - the alternative is to wait for Libero Reviewer to be released. This is not ideal from anyone's perspective so I think we are all making compromises.
