### ISSUE TITLE
Don't send email on form submission

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#240]
**User Story:**

As a submitter, I don't want to receive a confirmation email after I complete my initial submission.

**Product requirements/Acceptance criteria:**

From @hdrury1 in https://github.com/elifesciences/elife-xpub/issues/153#issuecomment-397272716:
> Upon form submission, the submitter SHOULD NOT receive an email. Instead, they should be redirected to their dashboard where they will see their most recent submission listed at the top of the page with its status updated to 'Awaiting Quality Checks'.

**Comment by dryhten** [comment]
What's the status of this issue? Is it assigned to anyone? Also, what I'm understanding from this and what Jen did in https://github.com/elifesciences/elife-xpub/pull/315 is that now we only send an e-mail to corresponding author if it's not the same as the submitter, is that true?

**Comment by jsms90** [comment]
Yes, sorry @dryhten. It became clear that it was easier to complete this issue whilst doing #310. So PR #315 solves both issues

**Comment by jsms90** [comment]
Also, to answer your question. Yes, that's exactly correct.

The Confirmation/Success email that we used to send to the submitter every time they clicked 'Submit' (which I believe you were working on before your holiday?) is now being removed by this issue, based on Hannah's request that you can see in the top comment.

A completely separate email is supposed to be sent to the Corresponding Author, if and only if, the Corresponding Author & the Submitter are different people. This was already added by Tam against issue #154 & you reviewed the PR which added it :+1: 

But at the end of last week, the product requirements for the email verification feature changed, so that we're now sending the author this email on 'Submit' rather than 'Next'. Which is why PR #315 removes the code that Tam added & also removes the notification ribbon from the wizard.

To see a full breakdown of the tasks associated with the email verification feature, see issue #272 & to see where the product requirements from this feature were first sent to us, see issue #204.

Happy to chat about this in person, if all these github issues are too confusing?
