### ISSUE TITLE
Remove green validation ring from successful inputs

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#303]
**Product requirements/Acceptance criteria:**

Functional:

Currently, successful validation results in a green border around input fields. This should be removed- rather, a submitter should just be able to progress to the next input/page. The first page of the wizard is a good example; at the moment there is a delay on clicking 'Next' whereby validation occurs and the green validation borders appear.

Visible feedback should only be given when validation is unsuccessful (with red border and validation wording). The current exception being the subject area input, which should continue to indicate that maximum 2 choices has been reached.

**Comment by jsms90** [comment]
So if a user cannot progress to the next page because some fields are invalid, they should be shown visual feedback on the **invalid** fields :+1: But in that same situation, should a user _also_ see a green border on the **valid** fields?

Or are you in fact saying that the "success" validation on input fields [in our invision styleguide](https://projects.invisionapp.com/share/NZKXOQUV4P3#/screens/302926985) should never be implemented?

**Comment by diversemix** [comment]
@jsms90 ... I think the consensus of @hdrury1 and @gmaciocci  was that showing green borders is never needed .. only showing red ones. (Happy to be corrected)

**Comment by jsms90** [comment]
Okie doke :+1:

There's one other situation in which we use the green success border - when a user has selected 2 options from the Subject Area Dropdown. This + the message below combine to give visual feedback to the user about why they can no longer open the dropdown menu.

Do you want to keep the green border (and message) in this situation?

**Comment by jsms90** [comment]
One other question - do you ever want the "warning" border (orange) that's listed in the component styleguide within invision?

If not, we can remove this function altogether (used in 3 places in our codebase)
```
const borderColor = ({ theme, validationStatus = 'default' }) =>
  ({
    error: theme.colorError,
    success: theme.colorSuccess,
    warning: theme.colorWarning,
    default: theme.colorBorder,
}[validationStatus])
```

and just handle the "error" situation

**Comment by hdrury1** [comment]
Hey @jsms90:

1) In general, we should remove the green verification success border. So, in the use case you mention when there are successes and errors on a page the user should only receive feedback for the errors.
2) One exception to the above (and only one so far, but there may be more in the future) is the subject area drop down. You can see on the hi-fi design [here](https://invis.io/B4MKNYSTRQZ#/304489195_wizard-Screen-3) that there is a green border + success message.
3) The only use we have for the organge warning currently is when a corresponding author is yet to accept their responsibilities (where are the other places in the codebase?) and in this instance it should remain as the submitter needs the visual feedback in order to remind them to take action (see hi-fi wireframe [here](https://invis.io/EYMKOI5HNJZ#/298836919_default-Page-Opt-In-Ribbon)).

**Comment by jsms90** [comment]
**Warning**
Point (3) will no longer happen, due to the change in requirements for the Corresponding Author email verification feature - see [this comment in issue #204](https://github.com/elifesciences/elife-xpub/issues/204#issuecomment-402965678)

So we do not currently have any requirements for a Warning colour/state? I would suggest that we remove this from the codebase altogether, to avoid confusion, until such time as we do have product requirements for it? But this is of course open for discussion.

**Success**
As for point (2) - so (for now), the only situation in which we need the green border & message is the Subject Area Dropdown? For this exact reason, I have implemented this component so that the success message lives inside `SubjectAreaDropdown` itself. Whereas the error messages are generated by the validation schema, which is applied to the whole form.

So, currently, error messages behave the same way across the form, regardless of the field they're being applied to. There is no concept of a success message on any of the fields except Subject Area Dropdown.

I suggest that we apply the same thinking to the border colour & restrict green-ifying to `SubjectAreaDropdown` alone, until such a time as our product requirements change.

---

On a completely separate note, in order to remove the green border from the rest of the fields, we need to make a change in pubsweet's `TextField` component (namely to remove this `borderColor` function, or at least the 'success' part). Does anyone happen to know whether this would introduce a breaking change to other applications who are using pubsweet? Or are we the only ones who apply `colorSuccess` to the border, based on the `validationStatus`?

In my view, this demonstrates a slight flaw in our frontend component architecture - the fact that `TextField` (and other atoms) are inextricably coupled with the `ValidatedField` component.

Imo, each of these atoms should not alter its own design based on the parent component that wraps it. Instead, I imagine that the component (`ValidatedField`) responsible for changing the state (i.e. `validationStatus`)  should also be the one responsible for applying the design changes.

**Comment by hdrury1** [comment]
Correct, due to new product requirements for corresponding author validation there is currently no call for the warning state.

**Comment by tamlyn** [comment]
Note that the delay when clicking "Next" is not due to validation (which happens as you type). It is due to sending the verification email (which currently happens every time, regardless of form input due to #293 and #309).
