### ISSUE TITLE
Scroll up to first validation error on clicking next

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#330]
**User Story:**

_As a submitter I want to see the validation errors when I click next._

**Product requirements/Acceptance criteria:**

Functional:
- Scroll up to first validation error on clicking next

**Comment by diversemix** [comment]
We may need some product input on this ... I would expect we would want to scroll up to the top of the most relevant control (given that validation errors are beneath the control)
/cc @hdrury1

**Comment by hdrury1** [comment]
Clicking 'Next' with validation errors on the page shuld cause the page to scroll up, and focus to jump to the first field with a validation error.

**Comment by chris-huggins** [comment]
I feel a little uneasy about this. Generally I think it's better to avoid scrolling automatically as it's not always clear why it's happened. I would like to keep this ticket as is, but I think it would be a good idea to test this thoroughly and consider if we should inform users in a different way.

Typically with validation we would hope to catch errors by showing errors states at the point that something incorrect is entered. This _should_ mean that when we need to scroll users to show them inputs that need fixing, it's because they have missed something entirely (e.g. adding suggested editors). 

Scrolling would bring these to their attention but may be a little jarring. We could use components such as the 'ribbon' (https://ui-patterns.elifesciences.org/?p=atoms-info-bar-attention) to give context or when auto-scrolling. Or it may be better to indicate the need to scroll up.

I'm not suggesting yet that we do anything differently - just sharing my thoughts - and will look into best practices.

**Comment by hdrury1** [comment]
I vote that we put a pin in this, pending user feedback.
