### ISSUE TITLE
show author full list of keywords associated with a person pod

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#352]
**User Story**

_As a submitter/editor/staff I would like to access a person's full list of keywords so that I can choose the most appropriate people to handle my submission based on their expertise._

**Product Requirements**

- ~A person's keywords within their pod should be limited to a number of characters based on screen real estate and beyond this limit, they should be truncated with an ellipsis~ - done via PR #406 

- Clicking on the ellipsis should open a tool tip with the full list of keywords

- Clicking off the tooltip should close the tooltip

**Designs to come**

**Comment by jsms90** [comment]
Oh actually, I seem to remember us talking about this when we were in Cambridge and suggesting that, instead of a tooltip, perhaps we enlarge the person pod & display all the keywords within the card instead?

**Comment by hdrury1** [comment]
@jsms90 No designs as yet but will have something for you before you start work on this.

**Comment by jsms90** [comment]
One thing that came up when the designs were first shown to developers was that there might be a better alternative to a tooltip. For example, there could be a down chevron which enlarges the whole person pod, so that it's big enough to show all of the information associated with that person at once. That way you wouldn't have the situation in which the tooltip with the extra keywords was covering other information on the page that you might want to see.

Moving this into the backlog, pending designs & further discussion

**Comment by hdrury1** [comment]
Closing as now obsolete
