### ISSUE TITLE
Refactor components into pages folder structure

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#367]
It's difficult to know where to put new components like the people picker within the current folder structure we're using for components.

Refactoring to a folder structure like so will help to make it clearer:
```
components/
|_pages/
  |_dashboard/
  |_login/
  ...
  |_submission-wizard/
    |_Author/
    |_Editors/
    |_Files/
    |_Submission
|_ui/
  |_atoms/
  |_molecules/
```

The `submission-wizard/` directory structure is based off of the steps on the submission form, and is based on the progress bar.

Variable references within the files need updating to reflect any renaming we're doing.

**Comment by tamlyn** [comment]
As discussed, structure looks good with the addition of a `steps` folder to contain the individual steps. 

Note that the people picker should be a separate package under `client` since it is intended to be contributed back to PubSweet. There will be a container component for it somewhere under `app`, though.

**Comment by damnhipster** [comment]
Moved over tasks to #386
