### ISSUE TITLE
Create manuscript metadata page layout (wireframe 006)

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#45]
### Wireframes
Overall page:
![metdata-page](https://user-images.githubusercontent.com/15656538/39183933-95a71cde-47b9-11e8-8a05-c80e1102bafe.png)

When a user checks the box, a border appears and a new field for entry:
![metadata-page-checked](https://user-images.githubusercontent.com/15656538/39184199-71091fc0-47ba-11e8-9ac4-260b7782d189.png)

![checkbox-requirements](https://user-images.githubusercontent.com/15656538/39184163-51764db8-47ba-11e8-8137-cb1acda9cfc5.png)

**Comment by jsms90** [comment]
### UX Questions
- Which are required fields? How do we show this to users before they click 'Next'?

**Subject area dropdown**
- Is a dropdown for 16-19 options user friendly enough?
https://medium.com/@kollinz/dropdown-alternatives-for-better-mobile-forms-53e40d641b53
https://uxplanet.org/ux-design-drop-downs-in-forms-c6943ec30037
https://www.formisimo.com/blog/why-are-drop-downs-and-select-boxes-bad-for-forms/  
https://ux.stackexchange.com/questions/79369/what-is-the-best-multi-select-filter-for-an-article-list

Suggestion is often to allow users to type into an autocomplete input field instead e.g. https://www.visionaustralia.org/services/digital-access/resources/autocomplete

- How does a user get away from the dropdown? Currently only seems possible by clicking away from the list, but this may not be obvious to users
- Somehow make it more obvious that there is a limit of 2 subject areas? e.g. 2 input boxes, 1 required & 1 not?

**Checkboxes**
Current implementation following requirements above:
- Different number of boxes for article name & article ID after checkbox 2 & 3?

![metadata-page-checkboxes](https://user-images.githubusercontent.com/15656538/39189034-25a0161a-47c9-11e8-8108-6529005a7420.png)

**Validation**
- Can we assume that users known their reference number?
- If validating on name, what happens if there is a slight typo?
- Does validation only occur after clicking 'Next'?

**Comment by g-sam** [comment]
pinging @NickDuf

**Comment by NickDuf** [comment]
@jsms90 here are some answers to your questions.

Which are required fields? How do we show this to users before they click 'Next'?
- Title, type, subjects (max of two choices to be made). If a checkbox type input is used that must also be validated to have input (checkbox 3 at least one of the inputs must have value). We will be placing a validation message in close proximity to the input. Designs for this are to come

Subject area dropdown: Is a dropdown for 16-19 options user friendly enough?
- Possibly not. You are currently working off some very lo-fi wires that lack a lot of detail. For now I would leave space for this option while we work on the control. 

Suggestion is often to allow users to type into an autocomplete input field instead e.g. https://www.visionaustralia.org/services/digital-access/resources/autocomplete
- Interestingly enough this was my first idea. It does assume that the author is aware of our complete subject area list though. It could also lend itself to allowing someone to try to add a subject that doesn't exist which we would then need to validate against.  

How does a user get away from the dropdown? Currently only seems possible by clicking away from the list, but this may not be obvious to users
- Control is being worked on

Somehow make it more obvious that there is a limit of 2 subject areas? e.g. 2 input boxes, 1 required & 1 not?
- Control is being worked on

Checkboxes: Current implementation following requirements above:

Different number of boxes for article name & article ID after checkbox 2 & 3?
- The above snip is accurate

Validation
- Can we assume that users known their reference number? - This is a reasonable question and I think this needs to be discussed with our editorial team. However, it is a common method for us to reference work with authors
- If validating on name, what happens if there is a slight typo? - The article title input should offer a list based on user input. The same as your vision Australia link does. There will be some instances when the paper isn't in the system yet and can't be validated. The title input then serves as reference for staff to make sure the related piece of work is reviewed by the same editors and reviewers if possible. How a connection is made in this instance is still to be defined
- Does validation only occur after clicking 'Next'? - How validation works is to be defined. The form is presented in two ways at present which I am uneasy about. Once this question is confidently answered this will have an impact on validation approach

**Comment by jsms90** [comment]
Thanks @NickDuf ! That's all really helpful.

@g-sam has just pointed out to me that there's a separate issue open for the multiselect #42 & Adam and Jure from Coko have both flagged that this would be useful to have in pubsweet. So I could finish off this page without the subject areas component for now if you like?

Is there a particular reason why the 2nd and 3rd checkboxes need to display a different number of further inputs? I only ask because it seems like a good situation to build one component and reuse it.

> The article title input should offer a list based on user input. The same as your vision Australia link does.

So would you like something like [this](http://downshift.netlify.com/?selectedKind=Examples&selectedStory=autosuggest&full=0&addons=1&stories=1&panelRight=0)? With each of the items in the dropdown being something like:
- 14107 Molecular basis for multimerization in the activation of the epidermal growth factor
- [ref no/article id] [article title]

**Comment by NickDuf** [comment]
@jsms90 I think it makes sense to get the page as far as you can leaving space for components that are under consideration. 

We could probably have the checkbox 3 input validate if an article is in the system or otherwise leaving it as free text if not giving us only one input.

If others have a need for a single text input based on a checkbox being selected, it is worth doing the work. From our point of view we would want to be able to add more components as needed though.

For your final question if an author added an id would it give them '14107 Molecular basis for multimerization in the activation of the epidermal growth factor'?
