### ISSUE TITLE
Add contextual titles to People Picker modal

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#457]
**User Story:**

_As a user I would like an indication of which team member(s) I am selecting whilst inside the people picker modal._

**Product requirements/Acceptance criteria:**

Functional:

- Depending on the context, the modal should display a relevant title. 
- If the user is selecting from the list of senior editors, the title should be "Choose Senior Editors".
- If the user is selecting from the list of reviewing editors, the title should be "Choose Reviewing Editors".
- Header should be formated as per fontSizeHeading1

**Relevant links to design(s):**

[InVision Screen](https://invis.io/9HLUEH9AXRF#/305823519_picker-Author)

**Comment by dryhten** [comment]
I assume the font is `fontHeading`? If so, the result doesn't look like what's on the styleguide, since this font is semibold. I attached an image with what it looks like right now

![people-picker-title](https://user-images.githubusercontent.com/1497469/43910736-8f6ae8c4-9bf5-11e8-96cd-db274ea7bb2a.png)

**Comment by hdrury1** [comment]
Should be an h2 (semibold, 22px)

**Comment by dryhten** [comment]
Not a big difference, H2 would look like this

![people-picker-title2](https://user-images.githubusercontent.com/1497469/43912178-74e9591e-9bf9-11e8-810f-89573bea6c2a.png)

**Comment by hdrury1** [comment]
Thanks @dryhten, h2 is right.
