### ISSUE TITLE
Store data disclosure agreement in database

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#490]
We will need to store a value on the manuscript to indicate the submitter has agreed to disclose their data. This should include the 'true/false' value along with the name of the person that signed the agreement.

**Comment by diversemix** [comment]
Being that in eJP this is stored as a PDF - should we generate that PDF at this point and store it alongside the manuscript? I'm thinking GDPR here ... ? (I'm hoping we can just generate it on export)

**Comment by jsms90** [comment]
:thinking: Yeah I think you're right about generating it on export. All the xpub app needs to know is whether someone has given their consent or not.  So I can't see any reason why we would need to store a PDF version of this page of our website, within our database. We're only making it in the first place for eJP's benefit, right? So generating on export seems appropriate.

Or is there something I'm not thinking of, @diversemix?

**Comment by diversemix** [comment]
This was more a question for product / GDPR compliance... we could generate a PDF that says anything - its more like whether we should be able to prove it was just generated the once at the time they consented - rather than generated after the fact. I suspect I'm letting my past court based tamper-proof evidence get the better of me :)

**Comment by jsms90** [comment]
> whether we should be able to prove it was just generated the once at the time they consented - rather than generated after the fact

Ooo very interesting! I definitely hadn't considered this.

Well, I assume we proceed without generating a PDF for now, until told otherwise?

**Comment by hdrury1** [comment]
I think PDF on submission is fine.

**Comment by jsms90** [comment]
@diversemix @damnhipster would you say that this was covered by PR #496?

**Comment by damnhipster** [comment]
Yes. If we want to generate a PDF on submission or export, we should do that on a separate issue, since this issue is about storing the preference in the database.

**Comment by jsms90** [comment]
@diversemix and I had a chat at standup this morning about potentially needing to save more things into the database than we are currently doing. Right now we save:
- submitter signature (i.e. the name that they type into that box)
- disclosure consent (boolean based on the checkbox being ticked or not)

Peter was saying we may want to save the date when they signed it too, because that info is needed in order to generate the PDF :+1: 

But thinking about it now, I imagine that we might be better off saving the date when they click "Submit", rather than the date when they fill in this step of the wizard? So I think that this is something we're better off filing under the "MECA export" epic on our roadmap & considering this ticket 'done' in terms of requirements for the "Disclosure page" epic?

Finally, just to be completely clear, I've checked by running this locally & I've definitely got these values being saved into our database.

Filling in this step of the wizard:
![image](https://user-images.githubusercontent.com/15656538/44785561-39990900-ab89-11e8-9a6f-93778708d947.png)

Gives this in `psql`:
![image](https://user-images.githubusercontent.com/15656538/44785499-03f42000-ab89-11e8-9963-d32cfd11e748.png)

But I'll raise a PR now to add `submitterSignature` and `disclosureConsent` to the migrations, so that this doesn't get missed during the work on "Use individual tables instead of "entities" #473 for the "Store the Data in a database" epic #425
