### ISSUE TITLE
Investigate node-replay issue

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#501]
**Describe the bug**
see https://elifesciences.slack.com/archives/C6LKMFK5Z/p1534505623000100

**Comment by tamlyn** [comment]
### Context

The error `RequestError: Error: POST https://sciencebeam-texture.elifesciences.org:443/api/convert?filename=manuscript.pdf refused: not recording and no network access` is nothing to do with ScienceBeam. It is `replay` telling you that it couldn't find a recorded response for the request and the current Replay mode doesn't allow it to access the network. This is in order to make tests consistent and repeatable.

### The issue

Why does the request not match the recorded response? Has something changed in the code and it is genuinely a different request? If not, what is different? Is it a platform dependent issue? Is there some unique header being added that we can exclude from the Replay matcher?

Unless this happens again, it is going to be hard to investigate.

**Comment by hdrury1** [comment]
If we are planning to no longer use the API is this a moot point?

**Comment by jsms90** [comment]
Aren't we still using ScienceBeam to create the PDF that goes to eJP? The only thing that's changed is that we don't have a preview page in our own app, right?

**Comment by tamlyn** [comment]
We'll be hosting our own instance of ScienceBeam instead of using `https://sciencebeam-texture.elifesciences.org` but I think we will still communicate with it via its HTTP API. Unless there's some other method of doing it.

**Comment by diversemix** [comment]
@tamlyn Could this have happened if `sciencebeam` was being re-deployed from underneath us?

**Comment by tamlyn** [comment]
No because the test has no network access so couldn't be affected by changes to ScienceBeam.

**Comment by hdrury1** [comment]
Closing as unable to recreate.
