### ISSUE TITLE
Create modal to end wizard

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#511]
**User Story:**

_As a submitter I want the option to edit my submission data before it is sent for assessment._

**Product requirements/Acceptance criteria:**

Functional:

- Modal should appear after the user hits 'Submit' on the final screen of the submission wizard.

- 'Back' should close the modal and return to last screen of the wizard. The user should then be able to navigate forward and back through the wizard to make any changes as before.

- 'Continue' should redirect to the Thank You page.

- Using the browser's back button should have the same effect as hitting 'Back' on the modal.

**Designs*

![image](https://user-images.githubusercontent.com/41907215/46814551-e661cb00-cd70-11e8-8f9f-664cbfe4b67e.png)

- After confirming their submission via the modal, the user should be redirected to a page which explains that their submission has been received. see #736

**Comment by jsms90** [comment]
For whoever picks this up, please see issue #779 for further explanation of the spacing, if needed.

I imagine that it might be best to edit our [`FormHeadings` component](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/ui/atoms/FormHeadings.js), to add top and bottom padding (rather than margin) to the `FormH2`, `FormH3`, in order to conform to the styleguide (see [the final comment on that issue](https://github.com/elifesciences/elife-xpub/issues/779#issuecomment-428996712))
![image](https://user-images.githubusercontent.com/41907215/46814770-540df700-cd71-11e8-88c7-5f3c837fac9e.png)

Then, in order to maintain the desired spacing on all the steps of the submission wizard, we could use grid-styled. See original discussion here - https://github.com/elifesciences/elife-xpub/issues/238
