### ISSUE TITLE
Derisk Authenticating against Profile Service

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#554]
See Roadmap

**Comment by tamlyn** [comment]
Just spoke to @thewilkybarkid who had a neat suggestion: instead of sharing sessions between the two apps, the eLife website can generate a magic link to automatically log users into xPub.

I've drawn a picture of what I think the [desired user flow](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkhbZUxpZmUgaG9tZXBhZ2VdXG5Me0xvZ2dlZCBpbiB0byBKb3VybmFsP31cblhEW3hQdWIgZGFzaGJvYXJkXVxuWExbeFB1YiBsb2dpbl1cbk9bT1JDaUQgbG9naW5dXG5cbkggLS0-fHN1Ym1pdCBteSByZXNlYXJjaHwgTFxuTC0tPnx5ZXN8IFhEXG5MLS0-fG5vfCBYTFxuWEwgLS0-fGxvZ2luIGJ1dHRvbnwgT1xuTyAtLT4gfGxvZ2lufCBYRCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19) is.

And [another picture](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcblxuSG9tZVtlTGlmZSBob21lcGFnZV1cblhEW3hQdWIgZGFzaGJvYXJkXVxuWExbeFB1YiBsb2dpbiBwYWdlXVxuWExbeFB1YiBsb2dpbiBwYWdlXVxuT1tPcmNpZCBsb2dpbl1cblxuWEEoeFB1YiBhdXRoIHNlcnZpY2UpXG5QKFByb2ZpbGVzIHNlcnZpY2UpXG5KKEpvdXJuYWwgc3VibWl0KVxuXG5MRXtMb2dnZWQgaW4gdG8gSm91cm5hbD99XG5cbkhvbWUgLS0-IHxzdWJtaXQgbXkgcmVzZWFyY2h8IExFXG5MRSAtLT4gfHllc3wgSiBcbkogLS0-IHxyZWRpcmVjdCB3aXRoIEpXVHwgWERcblxuWEwgLS0-IFBcblAtLi0-T1xuTy0uLT5QXG5QIC0tPiBYQVxuWEEgLS0-IHxyZWRpcmVjdCB3aXRoIEpXVHwgWERcblxuTEUgLS0-fG5vfCBYTCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19) of how this could be implemented. 

The only new bit of functionality is the **Journal submit** endpoint which would be part of Journal but have access to the xPub secret and therefore be able to generate a JWT asserting that the user with a given Orcid ID is logged in.

A new OAuth app also needs to be registered with the Profiles service and xPub config updated to use this instead of Orcid directly.

**Comment by tamlyn** [comment]
Hmmm but actually if a user logs in with xPub first, they still won't be logged in to Journal. Maybe we need [something more like this](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcblxuSG9tZVtlTGlmZSBob21lcGFnZV1cblhEW3hQdWIgZGFzaGJvYXJkXVxuWExbeFB1YiBsb2dpbiBwYWdlXVxuWExbeFB1YiBsb2dpbiBwYWdlXVxuT1tPcmNpZCBsb2dpbl1cblxuUChQcm9maWxlcyBzZXJ2aWNlKVxuSlMoSm91cm5hbCBzdWJtaXQpXG5KTChKb3VybmFsIGxvZ2luKVxuXG5MRXtMb2dnZWQgaW4gdG8gSm91cm5hbD99XG5cbkhvbWUgLS0-IHxzdWJtaXQgbXkgcmVzZWFyY2h8IExFXG5MRSAtLT4gfHllc3wgSlMgXG5KUyAtLT4gfHJlZGlyZWN0IHdpdGggSldUfCBYRFxuXG5YTCAtLT4gSkxcbkpMIC0uLT4gUFxuUC0uLT5PXG5PLS4tPlBcblAtLi0-SkxcbkpMLS0-SlNcbkxFIC0tPnxub3wgWEwiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ). 

The login button on the xPub login page points to `https://elifesciences.org/log-in`  same as the one on the main site header. That way Journal processes the login first and creates a session before creating a JWT and redirecting to xPub based on the referrer.

**Comment by thewilkybarkid** [comment]
We'd need to whitelist xPub for the referrer redirect (https://github.com/elifesciences/journal/blob/153a0955418eff7decccf62d04ced3915b55bd73/test/Controller/AuthenticationTest.php#L69-L105) and attach a JWT.

**Comment by thewilkybarkid** [comment]
Maybe xPub could link to https://elifesciences.org/submit, which would log you in to Journal, then redirect to xPub with the JWT? Means not much has to change.

**Comment by diversemix** [comment]
@thewilkybarkid / @tamlyn  .... [do you think this captures the flow](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgU1IgYXMgc3VibWl0LXJlc2VhcmNoXG4gICAgcGFydGljaXBhbnQgWEwgYXMgeHB1Yi1sb2dpblxuICAgIHBhcnRpY2lwYW50IEpMIGFzIGpvdXJuYWwtbG9naW5cbiAgICBwYXJ0aWNpcGFudCBKUyBhcyBqb3VybmFsLXN1Ym1pdFxuICAgIHBhcnRpY2lwYW50IFhEIGFzIHhwdWItZGFzaFxuXG5vcHQgTG9nZ2VkIEluXG5TUiAtPj4gSlM6IDxqb3VybmFsPi9zdWJtaXRcbkpTIC0-PiBYRDogcmVkaXJlY3RcbmVuZFxuXG5vcHQgTm90IExvZ2dlZCBJblxub3B0IFdpdGggTG9naW4gUGFnZVxuU1IgLT4-IFhMOiA8eHB1Yj4vbG9naW5cblhMIC0-PiBKTDogY2xpY2sgbG9naW5cbmVuZFxub3B0IFdpdGhvdXQgTG9naW4gUGFnZVxuU1IgLT4-IEpTOiA8am91cm5hbD4vc3VibWl0XG5KUyAtPj4gSkw6IHJlZGlyZWN0XG5lbmRcbkpMIC0-PiBKTDogQXV0aCB3aXRoIE9SQ0lEXG5KTCAtPj4gSlM6IHJlZGlyZWN0XG5KUyAtPj4gSlM6IENyZWF0ZSBKV1RcbkpTIC0-PiBYRDogcmVkaXJlY3RcbmVuZFxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0) for:
- being logged in.
- not being loggin in (without an xpub login page)
- not being loggin in (with an xpub login page)

**Comment by diversemix** [comment]
Ok ... [diagram updated again](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgU1IgYXMgc3VibWl0LXJlc2VhcmNoXG4gICAgcGFydGljaXBhbnQgWEwgYXMgeHB1Yi1sb2dpblxuICAgIHBhcnRpY2lwYW50IEpMIGFzIGpvdXJuYWwtbG9naW5cbiAgICBwYXJ0aWNpcGFudCBKUyBhcyBqb3VybmFsLXN1Ym1pdFxuICAgIHBhcnRpY2lwYW50IFhEIGFzIHhwdWItZGFzaFxuXG5vcHQgTG9nZ2VkIEluXG5TUiAtPj4gSlM6IDxqb3VybmFsPi9zdWJtaXRcbkpTIC0-PiBYRDogcmVkaXJlY3RcbmVuZFxuXG5vcHQgTm90IExvZ2dlZCBJblxub3B0IFdpdGggTG9naW4gUGFnZVxuU1IgLT4-IFhMOiA8eHB1Yj4vbG9naW5cblhMIC0-PiBKUzogY2xpY2sgbG9naW5cbmVuZFxuXG5vcHQgV2l0aG91dCBMb2dpbiBQYWdlXG5TUiAtPj4gSlM6IDxqb3VybmFsPi9zdWJtaXRcbmVuZFxuSlMgLT4-IEpMOiByZWRpcmVjdFxuSkwgLT4-IEpMOiBBdXRoIHdpdGggT1JDSURcbkpMIC0-PiBKUzogcmVkaXJlY3RcbkpTIC0-PiBKUzogQ3JlYXRlIEpXVFxuSlMgLT4-IFhEOiByZWRpcmVjdFxuZW5kXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ) @tamlyn  / @thewilkybarkid 

I suggest when we are happy with it I'll put it into `/docs` for future reference.

**Comment by tamlyn** [comment]
@diversemix as discussed, here's a [slightly modified sequence diagram](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgU1IgYXMgc3VibWl0LXJlc2VhcmNoXG4gICAgcGFydGljaXBhbnQgWEwgYXMgeHB1Yi1sb2dpblxuICAgIHBhcnRpY2lwYW50IEpMIGFzIGpvdXJuYWwtbG9naW5cbiAgICBwYXJ0aWNpcGFudCBKUyBhcyBqb3VybmFsLXN1Ym1pdFxuICAgIHBhcnRpY2lwYW50IFhEIGFzIHhwdWItZGFzaFxuXG5vcHQgTG9nZ2VkIEluXG5TUiAtPj4gSlM6IDxqb3VybmFsPi9zdWJtaXRcblxuZW5kXG5cbm9wdCBOb3QgTG9nZ2VkIEluXG5TUiAtPj4gWEw6IDx4cHViPi9sb2dpblxuWEwgLT4-IEpTOiBjbGljayBsb2dpblxuXG5KUyAtPj4gSkw6IHJlZGlyZWN0XG5KTCAtPj4gSkw6IEF1dGggd2l0aCBPUkNJRFxuSkwgLT4-IEpTOiByZWRpcmVjdFxuZW5kXG5KUyAtPj4gSlM6IENyZWF0ZSBKV1RcbkpTIC0-PiBYRDogcmVkaXJlY3RcblxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0). For simplicity it removes the *with login page* and *without login page* options since the login page should be ready very soon. It also routes all logins through the JWT generation step since Journal doesn't have a way to know whether a user is logged in to xPub or not.

**Comment by tamlyn** [comment]
See #632 for further details.
