### ISSUE TITLE
Show error message when user tries to upload wrong manuscript type

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#597]
**User Story:**

_As a submitter I want to be notified when I upload the wrong file type for manuscript._

**Product requirements/Acceptance criteria:**

Functional:
The dropzone molecule should show a helpful error message that the file type I uploaded as a manuscript is not accepted.

**Comment by dryhten** [comment]
@jsms90 @tamlyn From my understanding in this issue we had to show a more helpful error message to the user when the wrong manuscript type is uploaded. In that case #594 doesn't close it. I know this is possible to do because I played around with it. Should we reopen it?

**Comment by jsms90** [comment]
@dryhten I believe the reason this got closed is because the product requirements that we've been given were met through that PR. But I totally agree that we probably need to consider more cases. Have you seen my comment on the manuscript upload epic? Does this cover the question you're asking here?

**Comment by hdrury1** [comment]
Was hoping the wording in https://github.com/elifesciences/elife-xpub/issues/513 was a catch-all, i.e. can be used in cases where the file is over 100MB, or uploaded in an incorrect format.
