### ISSUE TITLE
Remove search box dropdown

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#629]
Currently the search box dropdown shows only a list of people that match the current input. This information is a duplicate of the returned person pods.

In the future, we may wish to consider an auto-suggest feature but this requires user testing to flesh out product requirements. For now we should remove the dropdown all together.

**Comment by dryhten** [comment]
I see two main approaches here:

1. We keep the react autosuggest and hide the suggestions list. There are multiple ways of doing this, the best one I can think of would be to remove the `onSuggestionsFetchRequested` prop that we pass to `Autosuggest` (commenting out one line).
2. Completely remove the react autosuggest component and replace it with a styled input field.

It all depends on how likely we are to come back to it later. If it's very likely I would go with approach 1 so we don't have to rewrite a bunch of code in the future (and I would also open an issue to keep track of it). If it's not that likely we can go with option 2 since it's not really an autosuggest element and the code might be confusing.
