### ISSUE TITLE
Create Journal endpoint to generate JWT for xPub

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#637]
**Product requirements/Acceptance criteria:**

Functional:
- Visiting the URL either:
   - if the user is currently authenticated with Journal, redirects to xPub with a JWT 
   - if the user is not authenticated with Journal, runs through the usual Journal login flow then redirects to xPub with a JWT
- The JWT should 
   - be signed with a secret that is shared with xPub
   - contain the authenticated user's elife ID
   - be provided as the hash portion of the redirect URL, e.g. `https://xpub.elifesciences.org/login#<JWT>`

**Comment by thewilkybarkid** [comment]
Use `/submit` on Journal. (Or be explicit and `/xpub`?) We should feature flag this so it's available on some environments. xPub URI should be configurable too. /cc @giorgiosironi

**Comment by giorgiosironi** [comment]
> should feature flag this

Definitely for rollout; ff it's intended to always stay disabled in some environments, it is real configuration (like Redis/Elasticache/filesystem cache) rather than a feature flag (that usually gets removed being forced to `false` or `true` everywhere)

> so it's available on some environments

Probably `continuumtest` at first, and `prod` when rolled out. To be precise also `continuumtestpreview` and `preview`, same rules.

`end2end` does not include xpub at the moment, however, I am inclined to bring `elife-xpub--end2end` to life due to this integration. Would be a general environment for _automated_ testing _across projects_, which `elife-xpub` doesn't do at the moment and which will be covered only for _manual_ testing with a staging environment.

> xPub URI should be configurable too

of course

**Comment by diversemix** [comment]
@thewilkybarkid ... do you have all the information you need? I would use `/submit` rather than '/xpub` but not aware of all the tech details that would drive this decision.

**Comment by diversemix** [comment]
Talking with @thewilkybarkid we spotted a subtlety ... as the "Submit my research" button will need to `/submit` (on journal) when logged in .... or to the intermediate  xPub "login" page if you are not logged in. (The xPub login page will go to `/submit` on journal when login button is pressed) (FYI: @tamlyn / @hdrury1 )

**Comment by tamlyn** [comment]
Yes that's right. Though it could be implemented that the button always goes to `/submit` and then the logic to decide on next steps goes there.

**Comment by diversemix** [comment]
Good suggestion ... though on chatting here, it seems that then the 'submit' would need to determine where the originating request was coming from and then where to redirect. Seems a little more messy to me than having the fn of the button change depending on your logged in state? What do you think?

**Comment by thewilkybarkid** [comment]
What's the expected structure of the JWT payload? @tamlyn @diversemix

**Comment by diversemix** [comment]
Over and above the standard fields https://en.wikipedia.org/wiki/JSON_Web_Token#Standard_fields ... I think we need (if available) "preferred name", email, ORCID

What do you think @tamlyn   ?

**Comment by thewilkybarkid** [comment]
So:

- `nbf` = current time
- `exp` = 60 seconds(?) from now
- `sub` = eLife profile ID

Do you need others?

**Comment by diversemix** [comment]
So I'd expect `iat` == `nbf` ... and `exp` to be probably more like an hour from `iat`

**Comment by hdrury1** [comment]
@thewilkybarkid or @diversemix could you confirm why this is blocked?

**Comment by thewilkybarkid** [comment]
@hdrury1 For details of what's actually required.

Using https://github.com/elifesciences/elife-xpub/issues/636#issuecomment-424689462 it's:

`iat` = current time
`exp` = 60 seconds(?) from now*
`id` = eLife profile ID

@diversemix @tamlyn?

\* Not sure it should be anywhere near as long as an hour, since it should be used immediately? (Generated, user redirected to xPub, token consumed.)

**Comment by tamlyn** [comment]
The [current plan](https://github.com/elifesciences/elife-xpub/issues/636#issuecomment-424689462) is to have the xPub token contain only the elife profile ID. That means we can treat the Journal generated token as a valid xPub token. We can implement an xPub endpoint to exchange the short lived Journal token for a longer lived xPub token with the same contents but what is the benefit of this vs making the Journal token longer lived?

**Comment by thewilkybarkid** [comment]
If there's no timing information then it could be replayed at any time?

**Comment by thewilkybarkid** [comment]
When you say expiry are you referring to the session inside xPub?

A new Journal JWT will be generated every time your browser goes to http://elifesciences.org/submit (and then immediately redirects to xPub with it). Although it's in the fragment, if this is intercepted somehow (eg the response headers are logged) it can be reused. If there's no timing information then it's the same value generated every time. (And if there's no `jti` handling then it can be used indefinitely.)

**Comment by diversemix** [comment]
@thewilkybarkid / @tamlyn ... do you think jumping on a call would be the best way to sort this?

**Comment by thewilkybarkid** [comment]
I understand how PubSweet's authentication works now.

I would still be more comfortable with keeping Journal and xPub separate, so rather than Journal generating the JWT that causes the user to be logged into xPub, generate a short-lived JWT that is just a claim that the user is logged into Journal. xPub can then do whatever it needs with that information (we already do this with the Hypothesis client). How much effort would this be on the xPub side?

**Comment by diversemix** [comment]
What is causing you to feel uncomfortable with xPub using Journal's JWT?

**Comment by diversemix** [comment]
Meeting today 11am here: meet.google.com/rgy-rmdw-zup

**Comment by thewilkybarkid** [comment]
Decision: implement https://github.com/elifesciences/elife-xpub/issues/637#issuecomment-425353202.

**Comment by thewilkybarkid** [comment]
https://github.com/elifesciences/journal/pull/1073
