### ISSUE TITLE
Fix inconsistencies in vertical spacing

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#840]
[This PR](https://github.com/elifesciences/elife-xpub/pull/837) brought to light that [vertical spacing](https://app.zeplin.io/project/5bacf042615a8b6e20e84a5f/screen/5bc0cddca55ed15fd3fb3973) from the style guide has not yet been implemented. 

We should introduce this to ensure consistent vertical spacing across the application.

**Designs**
From [Zeplin](https://app.zeplin.io/project/5bacf042615a8b6e20e84a5f/screen/5bc0cddca55ed15fd3fb3973)
![image](https://user-images.githubusercontent.com/15656538/47293584-6bb36e00-d602-11e8-9595-aacb86646745.png)

**Comment by jsms90** [comment]
I should point out now that we have 2 sets of Heading components
1. those used in the static pages: with padding above and below (as in the Zeplin/invision designs above) & no margin on the bottom, pushing them away from other components on the page
2. those used in the form: no padding above or below, but with bottom margin that pushes them away from other components on the page

If this is what is meant by "inconsistency" in this issue title, does that mean that we should be doing (1) for both situations?

---

There don't seem to be any designs for h5 or h6. I'm guessing that's because we're not using those headings anywhere. Is that correct?

---

The `Paragraph` component doesn't have any padding above or below, right? But it does have bottom margin that pushes its siblings away from it (24px below)

I'm not sure I quite understand the padding that relates to the `SmallParagraph` (aka "font size base small"). We can't add `3px` above and `15px` below the whole block, we can only add padding or margin to every line of text. Considering the fact that the `15px` on the bottom will change value, depending on how many lines are in the paragraph, I'm not entirely sure what the intention is here?

**Comment by hdrury1** [comment]
Closing as superseded by other design tweak tickets.
