### ISSUE TITLE
Send email to user chosen for soft launch

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#858]
**User Story:**

_As a submitter chosen for the 10% soft launch I want to easily be able to reaccess xPub in order to complete an in progress submission._

**Product requirements/Acceptance criteria:**

Functional:
- An email should be sent when an xPub user clicks 'New Submission'
- The email should be sent to the email account associated with the user
- A link embedded in the email should direct the user to their xPub dashboard
- Other email content to be defined

**Comment by diversemix** [comment]
Implement #935

**Comment by hdrury1** [comment]
Email content:

**Subject** Libero Submission System: New Submission
**From** editorial@elifesciences.org

Dear {user_firstName},

You have been randomly selected to be part of the initial group of authors given access to our brand new submission interface. 

Our aim is to create an application that makes the process of submitting your work to eLife as intuitive as possible and your feedback is invaluable in helping us to achieve this.

Please use the link below to access your new dashboard at any time and complete your initial submission:

[link to dashboard]

Best wishes,

Susanna

Susanna Richmond
Senior Editorial Assistant, eLife

eLife Sciences Publications, Ltd is a limited liability non-profit non-stock corporation incorporated in the State of Delaware, USA, with company number 5030732, and is registered in the UK with company number FC030576 and branch number BR015634 at the address, Westbrook Centre, Milton Road, Cambridge CB4 1YG.

**Comment by diversemix** [comment]
After discussion and conversations with @hdrury1  and @Cooryd ....The logic for the email is changing to send to the author's email ... when that field changes on the manuscript.

Turns out that less than 6% of elife profiles have an email address - so sending to that it a no-go.

Therefore we need to send to authors and their email is only supplied on the first page - so we will send it when that field changes in upateManuscript.
