### ISSUE TITLE
Make change to submit.elifesciences.org/

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#861]
eJP should redirect route of `https://submit.elifesciences.org/` to our ELB in AWS which will handle the 90% / 10% filtering.

**Comment by giorgiosironi** [comment]
Perhaps stating the obvious, but the redirect should be to:
```
https://elifesciences.org/submit
```
For `staging`, in case they have one:
```
https://continuumtest--cdn-journal.elifesciences.org/submit
```

**Comment by diversemix** [comment]
Also for more context:
![image](https://user-images.githubusercontent.com/8524685/51170907-7864fc80-18a7-11e9-87bd-2fe103413c70.png)

https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgU1IgYXMgU3RhcnRcbiAgICBwYXJ0aWNpcGFudCBFTCBhcyBlTGlmZVxuICAgIHBhcnRpY2lwYW50IEVKUCBhcyBlSlBcbiAgICBwYXJ0aWNpcGFudCBYUCBhcyB4UHViXG5cblNSLS0-PkVKUDogY2xpY2sgYnV0dG9uIG9yIGJyb3dzZSB0byBzdWJtaXQuZWxpZmVzY2llbmNlcy5vcmdcbkFjdGl2YXRlIEVKUFxuRUpQLS0-PkVMOiBSZWRpcmVjdCAnLycgdG8gZWxpZmVzY2llbmNlcy5vcmcvc3VibWl0XG5EZWFjdGl2YXRlIEVKUFxuXG5BY3RpdmF0ZSBFTFxuRUwtLT4-RUw6IEFwcGx5IEZpbHRlclxuRUwtPj5FSlA6IE5vdCBzZWxlY3RlZCBodHRwczovL3N1Ym1pdC5lbGlmZXNjaWVuY2VzLm9yZy9jZ2ktYmluL21haW4ucGxleFxuRUwtPj5YUDogU2VsZWN0ZWQ6IGh0dHBzOi8veHB1Yi5lbGlmZXNjaWVuY2VzLm9yZ1xuRGVhY3RpdmF0ZSBFTFxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0

**Comment by giorgiosironi** [comment]
Summary of today's call from the technical point of view:
- current homepage on EJP is a `301 Permanent Redirect` to `/cgi-bin/main.plex` with no `Cache-Control` so switching that to go to `/submit` may be problematic as people continue to see the old behavior cached
- even if we did that, people may submit in EJP because they are already in the system through deep links like https://submit.elifesciences.org/cgi-bin/main.plex?form_type=home

Waiting for access logs from EJP to compare the foot prints of users (ip and user agent) that click `/submit` on `elifesciences.org` with people that make an initial submission on EJP at:
https://submit.elifesciences.org/cgi-bin/main.plex?form_type=submit_ms_splash&...

```
SELECT COUNT(url), DATE(timestamp) FROM prod.journal WHERE timestamp >= "2019-01-01 00:00:00" AND url="/submit" GROUP BY DATE(timestamp)
```
gives from 100 to 300 clicks a day on `/submit`.

**Comment by giorgiosironi** [comment]
It looks like this should be in `In Progress` now?

**Comment by hdrury1** [comment]
Once I've had confirmation from Joel that this work is happening!

**Comment by hdrury1** [comment]
Closing off as obsolete. We were unable to implement a hard redirect, so are instead redirecting users from eJP's New Submission splash screen when they select to submit one of the 'Initial Submission' article types.
